<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Relatude.DB</RootNamespace>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Version>0.4.0.190</Version>
  </PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
	</ItemGroup>
</Project>
