using System.Text.Json;
using Relatude.DB.Datamodels;
using Relatude.DB.Datamodels.Properties;
using Relatude.RoundTripModels;

namespace Relatude.Datamodels;

/// <summary>
/// A serialized datamodel must deserialize back to an equivalent model: this is what JsonFile
/// datamodel sources rely on. Reuses the code-generation fixture, which covers every property
/// type, all relation shapes, embedded properties, references, interfaces and records.
/// </summary>
[TestClass]
public class DatamodelJsonRoundTripTests {

    static Datamodel buildOriginal(bool initialize) {
        var dm = new Datamodel();
        dm.Add<RtVehicle>();
        dm.Add<RtCar>();
        dm.Add<RtBoat>();
        dm.Add<RtEverything>();
        dm.Add<RtBook>();
        dm.Add<RtChapter>();
        dm.Add<IRtSection>();
        dm.Add<IRtParagraph>();
        dm.Add<RtPerson>();
        dm.Add<RtPassport>();
        dm.Add<RtTeam>();
        dm.Add<RtDoc>();
        dm.Add<RtNote>();
        dm.Add<IRtNamed>();
        dm.Add<RtNamedThing>();
        dm.Add<RtSection>();
        dm.Add<RtSpouseRel>();
        dm.Add<RtFriendsRel>();
        dm.Add<RtCarsRel>();
        dm.Add<RtPassportRel>();
        dm.Add<RtTeamsRel>();
        dm.Add<RtDocsRel>();
        dm.Add<RtAutoParent>(autoDeduceRelations: true);
        dm.Add<RtAutoChild>(autoDeduceRelations: true);
        if (initialize) dm.EnsureInitalization();
        return dm;
    }

    static string nodeTypeJson(NodeTypeModel t) => JsonSerializer.Serialize(new {
        t.Id,
        t.DatamodelSourceId,
        t.DatamodelSourceFilename,
        t.CodeName,
        t.Namespace,
        t.ModelType,
        t.IsInnerNode,
        t.Hidden,
        t.NameOfPublicIdProperty,
        t.NameOfInternalIdProperty,
        t.DataTypeOfPublicId,
        t.DataTypeOfInternalId,
        t.NameOfMetaProperty,
        t.NameOfCreatedUtcProperty,
        t.NameOfChangedUtcProperty,
        t.NameOfDisplayNameProperty,
        t.NameOfAddressProperty,
        t.TextIndex,
        t.SemanticIndex,
        t.InstantTextIndexing,
        t.TextIndexBoost,
        Parents = t.Parents.OrderBy(x => x).ToArray(),
        PropertyIds = t.Properties.Keys.OrderBy(x => x).ToArray(),
    });

    static string relationJson(RelationModel r) => JsonSerializer.Serialize(new {
        r.Id,
        r.DatamodelSourceId,
        r.DatamodelSourceFilename,
        r.Namespace,
        r.CodeName,
        r.RelationType,
        SourceTypes = r.SourceTypes.OrderBy(x => x).ToArray(),
        TargetTypes = r.TargetTypes.OrderBy(x => x).ToArray(),
        r.CodeNameSources,
        r.CodeNameTargets,
        r.MaxCountTo,
        r.MaxCountFrom,
        r.CultureSpecific,
        r.AutoGenerated,
        r.DisallowCircularReferences,
    });

    static string propertyJson(PropertyModel p) => JsonSerializer.SerializeToNode(p, p.GetType())!.ToJsonString();

    static void assertEquivalent(Datamodel dm1, Datamodel dm2) {
        CollectionAssert.AreEquivalent(dm1.NodeTypes.Keys.ToList(), dm2.NodeTypes.Keys.ToList(), "Node type ids differ. ");
        foreach (var id in dm1.NodeTypes.Keys)
            Assert.AreEqual(nodeTypeJson(dm1.NodeTypes[id]), nodeTypeJson(dm2.NodeTypes[id]), "Node type " + dm1.NodeTypes[id].FullName + " did not round-trip. ");
        CollectionAssert.AreEquivalent(dm1.Relations.Keys.ToList(), dm2.Relations.Keys.ToList(), "Relation ids differ. ");
        foreach (var id in dm1.Relations.Keys)
            Assert.AreEqual(relationJson(dm1.Relations[id]), relationJson(dm2.Relations[id]), "Relation " + dm1.Relations[id].CodeName + " did not round-trip. ");
        CollectionAssert.AreEquivalent(dm1.Properties.Keys.ToList(), dm2.Properties.Keys.ToList(), "Property ids differ. ");
        foreach (var id in dm1.Properties.Keys) {
            var p1 = dm1.Properties[id];
            var p2 = dm2.Properties[id];
            var name = dm1.NodeTypes[p1.NodeType].CodeName + "." + p1.CodeName;
            Assert.AreEqual(p1.GetType(), p2.GetType(), "Property " + name + " changed model type. ");
            Assert.AreEqual(propertyJson(p1), propertyJson(p2), "Property " + name + " did not round-trip. ");
        }
    }

    [TestMethod]
    public void SerializedDatamodel_DeserializesToEquivalentModel() {
        var dm1 = buildOriginal(initialize: true);
        var json = DatamodelJson.Serialize(dm1);
        var dm2 = DatamodelJson.Deserialize(json);
        Assert.IsFalse(dm2.HasInitialized(), "A deserialized datamodel must not be initialized. ");
        dm2.EnsureInitalization();
        assertEquivalent(dm1, dm2);
        // the code-added fixture types must carry the synthetic Code source through serialization:
        Assert.IsTrue(dm2.Sources.Any(s => s.Id == DatamodelSource.CodeSourceId && s.Type == DatamodelSourceType.Code));
        Assert.IsTrue(dm2.NodeTypes.Values.Where(t => t.Id != NodeConstants.BaseNodeTypeId).All(t => t.DatamodelSourceId == DatamodelSource.CodeSourceId));
    }

    [TestMethod]
    public void SerializedBeforeInitialization_DeserializesAndInitializes() {
        // a JsonFile source is always deserialized into an uninitialized model, so relation
        // auto-creation and reference resolving must work from the serialized form too:
        var json = DatamodelJson.Serialize(buildOriginal(initialize: false));
        var dm2 = DatamodelJson.Deserialize(json);
        dm2.EnsureInitalization();
        var dm1 = buildOriginal(initialize: true);
        assertEquivalent(dm1, dm2);
    }

    [TestMethod]
    public void PropertyModels_KeepConcreteTypes() {
        var dm1 = buildOriginal(initialize: true);
        var dm2 = DatamodelJson.Deserialize(DatamodelJson.Serialize(dm1));
        dm2.EnsureInitalization();
        // References derives from GuidArray: the discriminator, not inheritance, must decide:
        var pastCars = dm2.Properties.Values.First(p => p.CodeName == nameof(RtPerson.PastCars));
        Assert.AreEqual(typeof(ReferencesPropertyModel), pastCars.GetType());
        var relatedIds = dm2.Properties.Values.First(p => p.CodeName == nameof(RtEverything.RelatedIds));
        Assert.AreEqual(typeof(GuidArrayPropertyModel), relatedIds.GetType());
    }

    [TestMethod]
    public void ChecksumSerialization_IgnoresProvenanceButNotIndexSettings() {
        var dm1 = buildOriginal(initialize: true);
        var checksum1 = DatamodelJson.SerializeForChecksum(dm1);
        // provenance changes must not affect the checksum:
        var dm2 = buildOriginal(initialize: true);
        foreach (var t in dm2.NodeTypes.Values) { t.DatamodelSourceId = Guid.NewGuid(); t.DatamodelSourceFilename = "moved.json"; }
        foreach (var r in dm2.Relations.Values) { r.DatamodelSourceId = Guid.NewGuid(); r.DatamodelSourceFilename = "moved.json"; }
        dm2.Sources.Add(new DatamodelSource() { Id = Guid.NewGuid(), Name = "Other" });
        Assert.AreEqual(checksum1, DatamodelJson.SerializeForChecksum(dm2));
        // index-affecting settings on derived property models must affect it (this was lost with
        // non-polymorphic serialization):
        var dm3 = buildOriginal(initialize: true);
        var description = (StringPropertyModel)dm3.Properties.Values.First(p => p.CodeName == nameof(RtEverything.Description));
        description.IndexedByWords = !description.IndexedByWords;
        Assert.AreNotEqual(checksum1, DatamodelJson.SerializeForChecksum(dm3));
    }
}
