using System.Reflection;
using System.Text.Json;
using System.Text.Json.Nodes;
using Relatude.DB.Datamodels;
using Relatude.DB.Datamodels.Properties;

namespace Relatude.DB.NodeServer.ModelEditor;

/// <summary>
/// What the datamodel editor knows about the fields of a node type, a relation, a property and a
/// source beyond their CLR shape: labels, inline help, grouping and the editor to use where the type
/// alone does not say (a Guid that is a node type, a list of Guids that are node types). The shape
/// itself - which fields exist, their kinds, their defaults - comes from reflection over the model
/// classes, so a field added to a model class shows up here without anyone remembering to add it,
/// under "Advanced" with a label made from its name until it gets a catalog entry.
///
/// The same idea as <see cref="Settings.SettingsCatalog"/>, for the model classes. Field paths are the
/// JSON property names <see cref="DatamodelJson"/> writes, which the editor edits directly.
/// </summary>
public static class DatamodelCatalog {

    public sealed class FieldDefinition {
        public required string Path { get; init; }
        public required string Label { get; init; }
        public required string Help { get; init; }
        /// <summary>text, textarea, integer, number, toggle, tristate (a bool that may be unset), choice,
        /// guid, typeRef, typeRefs, relationRef, propertyRef, sourceRef, stringList, intList.</summary>
        public required string Editor { get; init; }
        public required string Group { get; init; }
        public int Order { get; init; }
        public string[]? Choices { get; init; }
        public JsonNode? Default { get; init; }
        public bool Optional { get; init; }
        public bool ReadOnly { get; init; }
    }
    sealed class Entry {
        public required string Label { get; init; }
        public required string Help { get; init; }
        public string Group { get; init; } = "General";
        public int Order { get; init; } = 100;
        public string? Editor { get; init; }
        public bool ReadOnly { get; init; }
    }
    public sealed class PropertyTypeDefinition {
        public required string Value { get; init; }
        public required string Label { get; init; }
        public required string Help { get; init; }
        public required string Group { get; init; }
    }

    // fields that are the model's own business, not the editor's: keys, derived values, internals
    static readonly HashSet<string> hiddenNodeTypeFields = ["Id", "Properties", "IsInterface", "CanInherit", "FullName"];
    static readonly HashSet<string> hiddenRelationFields = ["Id", "RelationClassType", "AutoGenerated"];
    static readonly HashSet<string> hiddenPropertyFields = ["Id", "NodeType", "PropertyType", "AutoAssigned", "NodeTypesNames", "InnerNodeTypesNames", "KeyPropertyName"];
    static readonly HashSet<string> hiddenSourceFields = ["Id"];

    static readonly Dictionary<string, Entry> nodeType = new(StringComparer.Ordinal) {
        ["CodeName"] = new() { Label = "Name", Help = "The class or interface name, as it appears in code and in queries.", Order = 1 },
        ["Namespace"] = new() { Label = "Namespace", Help = "The namespace the type lives in. Types with the same name in different namespaces are different types.", Order = 2 },
        ["ModelType"] = new() { Label = "Kind", Help = "Class, interface, record or struct. Interfaces can be implemented by several types and are implemented by the engine when no class does; a class can extend one class and implement any number of interfaces.", Order = 3 },
        ["Parents"] = new() { Label = "Inherits", Help = "The types this one extends or implements. Their properties become part of this type.", Editor = "typeRefs", Order = 4 },
        ["DatamodelSourceId"] = new() { Label = "Source", Help = "Which model source defines the type, and so which file it is written to when the model is activated.", Editor = "sourceRef", Order = 5 },
        ["DatamodelSourceFilename"] = new() { Label = "File", Help = "The file the type is written to, relative to the source's folder. Empty puts a new type in a file of its own, named after it.", Order = 6 },
        ["Hidden"] = new() { Label = "Hidden", Help = "Leaves the type out of listings, such as the query page's type list. Its nodes are still there.", Order = 7 },
        ["IsInnerNode"] = new() { Label = "Inner node type", Help = "The type only exists embedded inside another node's property (an Embedded property). It has no id set of its own and cannot be queried directly.", Group = "Advanced" },
        ["TextIndex"] = new() { Label = "Text index", Help = "Whether nodes of this type are in the free text index. Unset uses the database's default.", Group = "Text search", Order = 1 },
        ["SemanticIndex"] = new() { Label = "Semantic index", Help = "Whether nodes of this type get embeddings for similarity search. Needs an AI provider. Unset uses the database's default.", Group = "Text search", Order = 2 },
        ["InstantTextIndexing"] = new() { Label = "Index instantly", Help = "Index text as part of the transaction instead of in the background. Slower writes, immediately searchable.", Group = "Text search", Order = 3 },
        ["TextIndexBoost"] = new() { Label = "Text index boost", Help = "Weights hits on this type up or down in text search. 0 leaves the score alone.", Group = "Text search", Order = 4 },
        ["NameOfPublicIdProperty"] = new() { Label = "Public id member", Help = "The member holding the node's public id (a Guid or a string). Usually \"Id\".", Group = "System members", Order = 1 },
        ["DataTypeOfPublicId"] = new() { Label = "Public id type", Help = "Whether the public id is a Guid or a string.", Group = "System members", Order = 2 },
        ["NameOfInternalIdProperty"] = new() { Label = "Internal id member", Help = "The member holding the engine's integer id, when the type exposes it.", Group = "System members", Order = 3 },
        ["DataTypeOfInternalId"] = new() { Label = "Internal id type", Help = "The integer type of the internal id member.", Group = "System members", Order = 4 },
        ["NameOfMetaProperty"] = new() { Label = "Meta member", Help = "The member of type NodeMeta, giving access to revision, access and publishing data.", Group = "System members", Order = 5 },
        ["NameOfCreatedUtcProperty"] = new() { Label = "Created member", Help = "The DateTime member the engine stamps with the creation time.", Group = "System members", Order = 6 },
        ["NameOfChangedUtcProperty"] = new() { Label = "Changed member", Help = "The DateTime member the engine stamps with the last change.", Group = "System members", Order = 7 },
        ["NameOfDisplayNameProperty"] = new() { Label = "Display name member", Help = "The string member that receives the node's display name.", Group = "System members", Order = 8 },
        ["NameOfAddressProperty"] = new() { Label = "Address member", Help = "The string member holding the node's address (its URL path segment).", Group = "System members", Order = 9 },
        ["MinNoInstances"] = new() { Label = "Minimum instances", Help = "How many nodes of the type there have to be. Leave at the minimum value for no limit.", Group = "Constraints", Order = 1 },
        ["MaxNoInstances"] = new() { Label = "Maximum instances", Help = "How many nodes of the type there can be. Leave at the maximum value for no limit.", Group = "Constraints", Order = 2 },
        ["DefaultReadAccess"] = new() { Label = "Default read access", Help = "The user group new nodes of this type are readable by, as a group id. The unspecified group leaves it to the node.", Group = "Access", Order = 1 },
        ["DefaultEditAccess"] = new() { Label = "Default edit access", Help = "The user group new nodes of this type are editable by.", Group = "Access", Order = 2 },
        ["DefaultEditViewAccess"] = new() { Label = "Default edit view access", Help = "The user group that may view the edit form of new nodes of this type.", Group = "Access", Order = 3 },
        ["DefaultPublishAccess"] = new() { Label = "Default publish access", Help = "The user group that may publish new nodes of this type.", Group = "Access", Order = 4 },
    };
    static readonly Dictionary<string, Entry> relation = new(StringComparer.Ordinal) {
        ["CodeName"] = new() { Label = "Name", Help = "The relation class name. Application code refers to the relation by it.", Order = 1 },
        ["Namespace"] = new() { Label = "Namespace", Help = "The namespace of the relation class.", Order = 2 },
        ["RelationType"] = new() { Label = "Kind", Help = "OneOne: a symmetric pair (spouse). OneToOne: a directed chain (previous, next). OneToMany: a tree (parent, children). ManyMany: an undirected network. ManyToMany: a directed network.", Order = 3 },
        ["SourceTypes"] = new() { Label = "From types", Help = "The node types on the source side of the relation.", Editor = "typeRefs", Order = 4 },
        ["TargetTypes"] = new() { Label = "To types", Help = "The node types on the target side of the relation.", Editor = "typeRefs", Order = 5 },
        ["CodeNameSources"] = new() { Label = "Source side name", Help = "The name of the nested class for the source side, e.g. \"Parent\". Empty uses a generated name.", Order = 6 },
        ["CodeNameTargets"] = new() { Label = "Target side name", Help = "The name of the nested class for the target side, e.g. \"Children\".", Order = 7 },
        ["DatamodelSourceId"] = new() { Label = "Source", Help = "Which model source defines the relation.", Editor = "sourceRef", Order = 8 },
        ["DatamodelSourceFilename"] = new() { Label = "File", Help = "The file the relation is written to, relative to the source's folder.", Order = 9 },
        ["MaxCountFrom"] = new() { Label = "Max from a source", Help = "How many targets one source node may relate to. Leave at the maximum value for no limit.", Group = "Constraints", Order = 1 },
        ["MaxCountTo"] = new() { Label = "Max to a target", Help = "How many sources may relate to one target node. Leave at the maximum value for no limit.", Group = "Constraints", Order = 2 },
        ["DisallowCircularReferences"] = new() { Label = "No cycles", Help = "Rejects a link that would make a node reach itself through the relation.", Group = "Constraints", Order = 3 },
        ["CultureSpecific"] = new() { Label = "Per culture", Help = "Keeps separate links per culture.", Group = "Advanced" },
    };
    static readonly Dictionary<string, Entry> property = new(StringComparer.Ordinal) {
        ["CodeName"] = new() { Label = "Name", Help = "The member name, as it appears in code and in queries.", Order = 1 },
        ["Indexed"] = new() { Label = "Indexed", Help = "Keeps a value index for the property, so filtering and sorting on it do not scan. Indexed properties are also facets unless \"No facet\" is set.", Group = "Indexing", Order = 1 },
        ["NotFacet"] = new() { Label = "No facet", Help = "Keeps an indexed property out of the facet counts.", Group = "Indexing", Order = 2 },
        ["IndexType"] = new() { Label = "Index storage", Help = "Where the value index lives: in memory or in the persisted value index engine. Default follows the database's setting.", Group = "Indexing", Order = 3 },
        ["IndexBoost"] = new() { Label = "Index boost", Help = "Weights hits on this property up or down in text search.", Group = "Text search", Order = 9 },
        ["UniqueValues"] = new() { Label = "Unique values", Help = "No two nodes may hold the same value. Needs the property to be indexed.", Group = "Constraints", Order = 1 },
        ["DisplayName"] = new() { Label = "Part of display name", Help = "The value takes part in the node's display name.", Order = 3 },
        ["ExcludeFromTextIndex"] = new() { Label = "Not in text index", Help = "Leaves the value out of the free text index of the node.", Group = "Text search", Order = 1 },
        ["CultureSensitive"] = new() { Label = "Culture sensitive", Help = "Values are compared and sorted with culture rules.", Group = "Advanced" },
        ["CultureSpecific"] = new() { Label = "Per culture", Help = "Keeps a separate value per culture.", Group = "Advanced" },
        ["Internal"] = new() { Label = "Internal", Help = "An engine-owned property that is not part of the generated code.", Group = "Advanced", ReadOnly = true },
        ["ReadAccess"] = new() { Label = "Read access", Help = "The user group that may read the value, as a group id. Empty leaves it to the node.", Group = "Access", Order = 1 },
        ["WriteAccess"] = new() { Label = "Write access", Help = "The user group that may write the value.", Group = "Access", Order = 2 },
        // string
        ["TextIndexType"] = new() { Label = "Text index storage", Help = "Where the word index of this property lives.", Group = "Text search", Order = 4 },
        ["IndexedByWords"] = new() { Label = "Word index", Help = "The value is searchable word by word (WhereSearch, BM25 ranking).", Group = "Text search", Order = 2 },
        ["IndexedBySemantic"] = new() { Label = "Semantic index", Help = "The value gets an embedding for similarity search. Needs an AI provider.", Group = "Text search", Order = 3 },
        ["PropertyIdForEmbeddings"] = new() { Label = "Embeddings from", Help = "Another property whose text supplies the embedding for this one, when the two should share it.", Editor = "propertyRef", Group = "Text search", Order = 5 },
        ["PrefixSearch"] = new() { Label = "Prefix search", Help = "Allows searching on the beginning of the value (starts with).", Group = "Text search", Order = 6 },
        ["InfixSearch"] = new() { Label = "Infix search", Help = "Allows searching on any part of the value (contains). Costs more index space.", Group = "Text search", Order = 7 },
        ["MinWordLength"] = new() { Label = "Minimum word length", Help = "Shorter words are not indexed.", Group = "Text search", Order = 10 },
        ["MaxWordLength"] = new() { Label = "Maximum word length", Help = "Longer words are not indexed.", Group = "Text search", Order = 11 },
        ["IgnoreDuplicateEmptyValues"] = new() { Label = "Empty values may repeat", Help = "With unique values on, lets several nodes hold an empty value.", Group = "Constraints", Order = 5 },
        ["StringType"] = new() { Label = "Content", Help = "What kind of text the value holds, for editors and indexing.", Group = "Constraints", Order = 4 },
        ["RegularExpression"] = new() { Label = "Pattern", Help = "A regular expression the value has to match.", Group = "Constraints", Order = 6 },
        ["MinLength"] = new() { Label = "Minimum length", Help = "The shortest value allowed.", Group = "Constraints", Order = 2 },
        ["MaxLength"] = new() { Label = "Maximum length", Help = "The longest value allowed. Leave at the maximum value for no limit.", Group = "Constraints", Order = 3 },
        ["DefaultValue"] = new() { Label = "Default value", Help = "The value a new node starts with.", Order = 2 },
        // numbers and dates
        ["MinValue"] = new() { Label = "Minimum", Help = "The smallest value allowed. Leave at the type's minimum for no limit.", Group = "Constraints", Order = 2 },
        ["MaxValue"] = new() { Label = "Maximum", Help = "The largest value allowed. Leave at the type's maximum for no limit.", Group = "Constraints", Order = 3 },
        ["FacetRangePowerBase"] = new() { Label = "Facet range base", Help = "Groups facet values into ranges growing by this power (e.g. 10 gives 1-10, 10-100, ...). 0 uses each value as its own facet.", Group = "Indexing", Order = 5 },
        ["FacetRangeCount"] = new() { Label = "Facet range count", Help = "How many ranges to split the values into. 0 uses each value as its own facet.", Group = "Indexing", Order = 6 },
        ["IsEnum"] = new() { Label = "Enum", Help = "The value is an enum member stored as its integer.", Group = "Constraints", Order = 7 },
        ["FullEnumTypeName"] = new() { Label = "Enum type", Help = "The full name of the enum type in the application.", Group = "Constraints", Order = 8 },
        ["LegalValues"] = new() { Label = "Legal values", Help = "The integer values allowed, in the same order as the names below.", Editor = "intList", Group = "Constraints", Order = 9 },
        ["LegalValueNames"] = new() { Label = "Value names", Help = "The name of each legal value, in the same order.", Editor = "stringList", Group = "Constraints", Order = 10 },
        // references and embedded
        ["NodeTypes"] = new() { Label = "Node types", Help = "The node types the reference may point at.", Editor = "typeRefs", Order = 4 },
        ["IncludeTypes"] = new() { Label = "Include", Help = "Whether descendants of the listed types are allowed too.", Order = 5 },
        ["ReferenceValueType"] = new() { Label = "Code shape", Help = "How the member is declared in code: the Reference/References wrapper, or a plain node-typed member or collection.", Group = "Code", Order = 1 },
        ["EmbeddedValueType"] = new() { Label = "Shape", Help = "A single inner node, a list, or a map keyed by a property.", Order = 4 },
        ["InnerNodeTypes"] = new() { Label = "Inner node types", Help = "The inner node types that may be embedded here.", Editor = "typeRefs", Order = 5 },
        ["KeyProperty"] = new() { Label = "Key property", Help = "For a map: the inner node property that is the key.", Editor = "propertyRef", Order = 6 },
        ["PrependOnAdd"] = new() { Label = "Prepend on add", Help = "New inner nodes go first instead of last.", Group = "Advanced" },
        // relation properties
        ["RelationId"] = new() { Label = "Relation", Help = "The relation this member gives access to.", Editor = "relationRef", Order = 4 },
        ["FromTargetToSource"] = new() { Label = "Points from target to source", Help = "The member sits on the target side of the relation and points back at sources.", Order = 5 },
        ["IsMany"] = new() { Label = "Many", Help = "The member holds a collection of related nodes rather than one.", Order = 6 },
        ["NodeTypeOfRelated"] = new() { Label = "Related type", Help = "The node type of the related nodes, when narrower than the relation's other side.", Editor = "typeRef", Order = 7 },
        ["RelationValueType"] = new() { Label = "Code shape", Help = "How the member is declared in code: a collection, list, array, enumerable or the native relation class.", Group = "Code", Order = 1 },
        ["IsNative"] = new() { Label = "Native relation member", Help = "The member is declared with the relation's own nested class rather than a plain node type.", Group = "Code", Order = 2 },
        ["Facet"] = new() { Label = "Facet", Help = "Counts the related nodes as facet values in searches.", Group = "Indexing", Order = 4 },
        ["TextIndexRelatedDisplayName"] = new() { Label = "Index related display names", Help = "The display names of related nodes become part of this node's text index.", Group = "Text search", Order = 12 },
        ["TextIndexRelatedContent"] = new() { Label = "Index related content", Help = "The text of related nodes becomes part of this node's text index.", Group = "Text search", Order = 13 },
        ["TextIndexRecursiveLevelLimit"] = new() { Label = "Related content depth", Help = "How many relation hops the related content indexing follows.", Group = "Text search", Order = 14 },
        // files
        ["FileStorageProviderId"] = new() { Label = "File store", Help = "The file store (from the storage settings) the files of this property go into, by id. Empty uses the first one.", Group = "Advanced" },
    };
    static readonly Dictionary<string, Entry> source = new(StringComparer.Ordinal) {
        ["Name"] = new() { Label = "Name", Help = "What this source is called. A label only - the model refers to it by id.", Order = 1 },
        ["Type"] = new() { Label = "Kind", Help = "Where the types are read from. An assembly namespace or a single type name uses classes compiled into the application. C# files are compiled while the database opens. JSON files hold the model itself.", Order = 2 },
        ["Enabled"] = new() { Label = "Loaded", Help = "Off skips the source entirely: its types leave the model at the next open.", Order = 3 },
        ["Reference"] = new() { Label = "Reference", Help = "For an assembly source, the assembly name (without .dll; empty is the entry assembly). For a type name source, the full type name, assembly qualified unless in the entry assembly. For a JSON source read through a provider, the file name.", Order = 4 },
        ["Namespace"] = new() { Label = "Namespace", Help = "For an assembly source, the namespace holding the model classes (required). For C# files, an optional filter.", Order = 5 },
        ["Filepath"] = new() { Label = "File or folder", Help = "For C# and JSON sources: a file, or a folder whose files are all loaded. Relative to the settings folder. Empty uses Models/CSharp or Models/Json.", Order = 6 },
        ["FileIO"] = new() { Label = "Read through provider", Help = "For a JSON source: a storage provider to read the file from instead of the file system.", Editor = "guid", Group = "Advanced" },
        ["SourceCodePath"] = new() { Label = "Source code folder", Help = "For a compiled source: the folder holding its C# files. With it set, the editor can write changes back; the application then has to be rebuilt and restarted.", Order = 7 },
        ["AutoDeduceRelations"] = new() { Label = "Node properties become relations", Help = "Turns plain node-typed properties into automatically created relations, the way earlier versions did. Off makes them Reference/References properties.", Group = "Advanced" },
    };

    static readonly PropertyTypeDefinition[] propertyTypes = [
        new() { Value = "String", Label = "Text", Help = "A string, with optional word, semantic, prefix and infix indexing.", Group = "Values" },
        new() { Value = "Integer", Label = "Integer", Help = "A 32-bit integer, also used for enums.", Group = "Values" },
        new() { Value = "Long", Label = "Long integer", Help = "A 64-bit integer.", Group = "Values" },
        new() { Value = "Double", Label = "Double", Help = "A double precision number.", Group = "Values" },
        new() { Value = "Float", Label = "Float", Help = "A single precision number.", Group = "Values" },
        new() { Value = "Decimal", Label = "Decimal", Help = "An exact decimal number, for money.", Group = "Values" },
        new() { Value = "Boolean", Label = "Boolean", Help = "True or false.", Group = "Values" },
        new() { Value = "DateTime", Label = "Date and time", Help = "A UTC date and time.", Group = "Values" },
        new() { Value = "DateTimeOffset", Label = "Date, time and offset", Help = "A date and time with its UTC offset.", Group = "Values" },
        new() { Value = "TimeSpan", Label = "Duration", Help = "A length of time.", Group = "Values" },
        new() { Value = "Guid", Label = "Guid", Help = "A globally unique id.", Group = "Values" },
        new() { Value = "GeoCoordinate", Label = "Geo coordinate", Help = "A latitude and longitude, with distance and within-radius queries.", Group = "Values" },
        new() { Value = "StringArray", Label = "Text list", Help = "A list of strings, each a facet value.", Group = "Collections" },
        new() { Value = "GuidArray", Label = "Guid list", Help = "A list of guids.", Group = "Collections" },
        new() { Value = "FloatArray", Label = "Vector", Help = "A list of floats, e.g. an embedding.", Group = "Collections" },
        new() { Value = "EnumArray", Label = "Enum list", Help = "A list of enum members.", Group = "Collections" },
        new() { Value = "ByteArray", Label = "Bytes", Help = "Raw bytes stored on the node.", Group = "Special" },
        new() { Value = "File", Label = "File", Help = "A file kept in a file store, with previews and conversions.", Group = "Special" },
        new() { Value = "Embedded", Label = "Embedded nodes", Help = "Inner nodes stored inside this node: one, a list or a map.", Group = "Links" },
        new() { Value = "Reference", Label = "Reference", Help = "A link to one node, stored on this node.", Group = "Links" },
        new() { Value = "References", Label = "References", Help = "Links to several nodes, stored on this node.", Group = "Links" },
        new() { Value = "Relation", Label = "Relation member", Help = "Access to one side of a relation defined in the model.", Group = "Links" },
    ];

    static readonly Lazy<object> schema = new(build);
    /// <summary>The whole schema, built once; it only depends on the model classes.</summary>
    public static object Schema => schema.Value;

    static object build() {
        var common = fields(typeof(PropertyModel), property, hiddenPropertyFields, null);
        var commonPaths = common.Select(f => f.Path).ToHashSet();
        var byType = new Dictionary<string, FieldDefinition[]>();
        foreach (var pt in propertyTypes) {
            var type = PropertyModelJsonConverter.GetModelType(Enum.Parse<PropertyType>(pt.Value));
            byType[pt.Value] = fields(type, property, hiddenPropertyFields, commonPaths);
        }
        return new {
            NodeType = fields(typeof(NodeTypeModel), nodeType, hiddenNodeTypeFields, null),
            Relation = fields(typeof(RelationModel), relation, hiddenRelationFields, null),
            PropertyCommon = common,
            PropertyByType = byType,
            PropertyTypes = propertyTypes,
            Source = fields(typeof(DatamodelSource), source, hiddenSourceFields, null),
            Groups = new[] { "General", "Indexing", "Text search", "Constraints", "System members", "Access", "Code", "Advanced" },
        };
    }

    /// <summary>The catalogued names for a class, so a test can check the catalog against the class.</summary>
    public static IEnumerable<string> CataloguedPaths(Type type) {
        var entries = type == typeof(NodeTypeModel) ? nodeType : type == typeof(RelationModel) ? relation : type == typeof(DatamodelSource) ? source : property;
        return entries.Keys;
    }
    public static IEnumerable<string> HiddenPaths(Type type) {
        return type == typeof(NodeTypeModel) ? hiddenNodeTypeFields : type == typeof(RelationModel) ? hiddenRelationFields : type == typeof(DatamodelSource) ? hiddenSourceFields : hiddenPropertyFields;
    }

    static FieldDefinition[] fields(Type type, Dictionary<string, Entry> entries, HashSet<string> hidden, HashSet<string>? exclude) {
        object? instance = null;
        try { instance = Activator.CreateInstance(type); } catch { }
        var list = new List<FieldDefinition>();
        foreach (var p in type.GetProperties(BindingFlags.Public | BindingFlags.Instance)) {
            if (hidden.Contains(p.Name) || exclude != null && exclude.Contains(p.Name)) continue;
            if (p.GetIndexParameters().Length > 0) continue;
            if (p.SetMethod == null || !p.SetMethod.IsPublic) continue;
            if (p.GetCustomAttribute<System.Text.Json.Serialization.JsonIgnoreAttribute>() != null) continue;
            var valueType = Nullable.GetUnderlyingType(p.PropertyType) ?? p.PropertyType;
            var isNullable = Nullable.GetUnderlyingType(p.PropertyType) != null || !p.PropertyType.IsValueType;
            entries.TryGetValue(p.Name, out var entry);
            var editor = entry?.Editor ?? editorFor(p.PropertyType, valueType);
            JsonNode? defaultValue = null;
            if (instance != null) {
                try { defaultValue = JsonSerializer.SerializeToNode(p.GetValue(instance), p.PropertyType, DatamodelJson.Options); } catch { }
            }
            list.Add(new FieldDefinition {
                Path = p.Name,
                Label = entry?.Label ?? humanize(p.Name),
                Help = entry?.Help ?? "",
                Editor = editor,
                Group = entry?.Group ?? "Advanced",
                Order = entry?.Order ?? 100,
                Choices = valueType.IsEnum ? Enum.GetNames(valueType) : null,
                Default = defaultValue,
                Optional = isNullable,
                ReadOnly = entry?.ReadOnly ?? false,
            });
        }
        return list.OrderBy(f => Array.IndexOf(groupOrder, f.Group) is var i && i < 0 ? 99 : i).ThenBy(f => f.Order).ThenBy(f => f.Label).ToArray();
    }
    static readonly string[] groupOrder = ["General", "Indexing", "Text search", "Constraints", "System members", "Access", "Code", "Advanced"];
    static string editorFor(Type declared, Type valueType) {
        if (valueType == typeof(bool)) return Nullable.GetUnderlyingType(declared) != null ? "tristate" : "toggle";
        if (valueType == typeof(int) || valueType == typeof(long) || valueType == typeof(short) || valueType == typeof(byte)) return "integer";
        if (valueType == typeof(double) || valueType == typeof(float) || valueType == typeof(decimal)) return "number";
        if (valueType == typeof(string)) return "text";
        if (valueType == typeof(Guid)) return "guid";
        if (valueType.IsEnum) return "choice";
        if (valueType == typeof(List<Guid>) || valueType == typeof(Guid[])) return "typeRefs";
        if (valueType == typeof(List<string>) || valueType == typeof(string[])) return "stringList";
        if (valueType == typeof(int[]) || valueType == typeof(List<int>)) return "intList";
        if (valueType == typeof(DateTime) || valueType == typeof(DateTimeOffset) || valueType == typeof(TimeSpan)) return "text";
        return "text";
    }
    static string humanize(string name) {
        var sb = new System.Text.StringBuilder();
        for (var i = 0; i < name.Length; i++) {
            var c = name[i];
            if (i > 0 && char.IsUpper(c) && !char.IsUpper(name[i - 1])) sb.Append(' ');
            sb.Append(i == 0 ? c : char.ToLowerInvariant(c));
        }
        return sb.ToString();
    }
}
