// The data model editor's half of the wire. See UIDatamodel.cs: the model travels as the JSON the
// server's own DatamodelJson writes (PascalCase keys, types/relations/properties keyed by id), and the
// editor edits that object directly and posts it back whole as the draft. Everything else here is
// camelCased like the rest of the admin API.

import { send } from "./channel";

// ---- the model, as DatamodelJson writes it ----

export type ModelKind = "Class" | "Interface" | "Record" | "Struct";
export type RelationKind = "OneOne" | "OneToOne" | "OneToMany" | "ManyMany" | "ManyToMany";
export type SourceType = "AssemblyNameReference" | "TypeNameReference" | "JsonFile" | "CSharpCodeFile" | "Code";

/** A property as the model serializes it. Only the fields the editor reads by name are typed; the
    rest are edited through the schema and ride along untouched. */
export interface PropertyJson {
  Id: string;
  CodeName: string;
  PropertyType: string;
  NodeType?: string;
  Indexed?: boolean;
  Internal?: boolean;
  DisplayName?: boolean;
  IndexedByWords?: boolean;
  IndexedBySemantic?: boolean;
  UniqueValues?: boolean;
  RelationId?: string;
  IsMany?: boolean;
  FromTargetToSource?: boolean;
  NodeTypeOfRelated?: string;
  NodeTypes?: string[];
  InnerNodeTypes?: string[];
  AutoAssigned?: boolean;
  [key: string]: unknown;
}

export interface NodeTypeJson {
  Id: string;
  DatamodelSourceId: string;
  DatamodelSourceFilename?: string | null;
  CodeName: string;
  Namespace?: string | null;
  ModelType: ModelKind;
  Parents: string[];
  Properties: Record<string, PropertyJson>;
  Hidden?: boolean;
  IsInnerNode?: boolean;
  TextIndex?: boolean | null;
  SemanticIndex?: boolean | null;
  [key: string]: unknown;
}

export interface RelationJson {
  Id: string;
  DatamodelSourceId: string;
  DatamodelSourceFilename?: string | null;
  CodeName: string;
  Namespace?: string | null;
  RelationType: RelationKind;
  SourceTypes: string[];
  TargetTypes: string[];
  CodeNameSources?: string | null;
  CodeNameTargets?: string | null;
  AutoGenerated?: boolean;
  [key: string]: unknown;
}

export interface SourceJson {
  Id: string;
  Name?: string | null;
  Namespace?: string | null;
  Type: SourceType;
  Filepath?: string | null;
  Reference?: string | null;
  FileIO?: string | null;
  SourceCodePath?: string | null;
  Enabled: boolean;
  AutoDeduceRelations: boolean;
  [key: string]: unknown;
}

export interface ModelJson {
  NodeTypes: Record<string, NodeTypeJson>;
  Relations: Record<string, RelationJson>;
  Sources: SourceJson[];
  [key: string]: unknown;
}

// ---- what the page gets ----

export interface DraftInfo {
  savedUtc: string;
  checksum: string;
  baseChecksum: string | null;
  awaitingRebuild: boolean;
  awaitingRebuildSinceUtc: string | null;
  note: string | null;
  model: ModelJson | null;
}

export interface HistoryEntry {
  key: string;
  savedUtc: string;
  /** "open" (found active when the database opened), "replaced" (what an activation replaced) */
  reason: string;
  checksum: string;
  nodeTypes: number;
  relations: number;
  properties: number;
  size: number;
}

export interface SourceInfo {
  id: string;
  name: string;
  type: SourceType;
  enabled: boolean;
  namespace: string | null;
  filepath: string | null;
  reference: string | null;
  fileIO: string | null;
  sourceCodePath: string | null;
  autoDeduceRelations: boolean;
  /** the synthetic source of types registered from application code (OnDatamodelInit) */
  isCode: boolean;
  inSettings: boolean;
  writable: boolean;
  readOnlyReason: string | null;
  /** a write into this source takes effect after the application is rebuilt and restarted */
  requiresRebuild: boolean;
  resolvedPath: string | null;
  pathExists: boolean | null;
  typeCount: number;
  relationCount: number;
  files: string[];
}

export interface DatamodelPage {
  storeId: string;
  open: boolean;
  state: string;
  rootFolder: string;
  baseTypeId: string;
  codeSourceId: string;
  active: { checksum: string; model: ModelJson } | null;
  activeError: string | null;
  draft: DraftInfo | null;
  draftError: string | null;
  history: HistoryEntry[];
  typeCounts: Record<string, number>;
  sources: SourceInfo[];
  /** the source list is set by the configuration overlay and cannot be changed from here */
  sourcesLocked: boolean;
  ioProviders: { id: string; name: string | null }[];
}

// ---- the schema of the editors ----

export type FieldEditor =
  | "text"
  | "textarea"
  | "integer"
  | "number"
  | "toggle"
  | "tristate"
  | "choice"
  | "guid"
  | "typeRef"
  | "typeRefs"
  | "relationRef"
  | "propertyRef"
  | "sourceRef"
  | "stringList"
  | "intList";

export interface FieldDef {
  path: string;
  label: string;
  help: string;
  editor: FieldEditor;
  group: string;
  order: number;
  choices: string[] | null;
  default: unknown;
  optional: boolean;
  readOnly: boolean;
}

export interface PropertyTypeDef {
  value: string;
  label: string;
  help: string;
  group: string;
}

export interface Schema {
  nodeType: FieldDef[];
  relation: FieldDef[];
  propertyCommon: FieldDef[];
  propertyByType: Record<string, FieldDef[]>;
  propertyTypes: PropertyTypeDef[];
  source: FieldDef[];
  groups: string[];
}

// ---- validation and activation ----

export type IssueSeverity = "error" | "warning" | "info";

export interface Issue {
  severity: IssueSeverity;
  code: string;
  message: string;
  nodeTypeId: string | null;
  propertyId: string | null;
  relationId: string | null;
  sourceId: string | null;
  file: string | null;
}

export interface SourceChange {
  sourceId: string;
  name: string;
  type: SourceType;
  writable: boolean;
  readOnlyReason: string | null;
  requiresRebuild: boolean;
  removed: boolean;
  added: boolean;
  addedTypes: string[];
  changedTypes: string[];
  removedTypes: string[];
  addedRelations: string[];
  changedRelations: string[];
  removedRelations: string[];
  hasModelChanges: boolean;
}

export interface PlannedFile {
  sourceId: string;
  path: string;
  relativePath: string;
  action: "write" | "delete";
  exists: boolean;
  changed: boolean;
  nodeTypeIds: string[];
  relationIds: string[];
  content: string | null;
}

export interface Plan {
  settingsChange: boolean;
  requiresRebuild: boolean;
  sources: SourceChange[];
  files: PlannedFile[];
}

export interface Validation {
  issues: Issue[];
  hasErrors: boolean;
  hasWarnings: boolean;
  compiled: boolean;
  requiresRebuild: boolean;
  draftChecksum: string;
  activeChecksum: string;
  plan: Plan | null;
}

export interface ActivationResult {
  validation: Validation;
  needsConfirmation: boolean;
  activated: boolean;
  awaitingRebuild: boolean;
  reopened: boolean;
  settingsChanged: boolean;
  filesWritten: string[];
  filesDeleted: string[];
  checksumMatches: boolean | null;
  message: string | null;
}

// ---- calls ----

export function fetchDatamodel(storeId: string): Promise<DatamodelPage> {
  return send<DatamodelPage>("datamodel", { storeId });
}

let schemaPromise: Promise<Schema> | null = null;
/** The editor schema only depends on the server's model classes, so one fetch serves the session. */
export function fetchSchema(): Promise<Schema> {
  if (!schemaPromise) {
    schemaPromise = send<Schema>("datamodel-schema").catch((e) => {
      schemaPromise = null;
      throw e;
    });
  }
  return schemaPromise;
}

export function saveDraft(storeId: string, model: ModelJson, note?: string | null): Promise<DraftInfo> {
  return send<DraftInfo>("datamodel-draft-save", { storeId, model, note: note ?? null });
}

export function discardDraft(storeId: string): Promise<void> {
  return send("datamodel-draft-discard", { storeId }).then(() => undefined);
}

export function validateDraft(storeId: string, model: ModelJson, dryRun: boolean): Promise<Validation> {
  return send<Validation>("datamodel-validate", { storeId, model, dryRun });
}

export function activateDraft(storeId: string, model: ModelJson, acceptWarnings: boolean, note?: string | null): Promise<ActivationResult> {
  return send<ActivationResult>("datamodel-activate", { storeId, model, acceptWarnings, note: note ?? null });
}

export function loadHistory(storeId: string, key: string): Promise<HistoryEntry & { model: ModelJson }> {
  return send<HistoryEntry & { model: ModelJson }>("datamodel-history-load", { storeId, key });
}

export function deleteHistory(storeId: string, key: string): Promise<boolean> {
  return send<{ deleted: boolean }>("datamodel-history-delete", { storeId, key }).then((r) => r.deleted);
}

export function exportModel(
  storeId: string,
  model: ModelJson | null,
  format: "csharp" | "json",
  attributes = true,
): Promise<{ content: string; fileName: string; contentType: string }> {
  return send("datamodel-export", { storeId, model, format, attributes });
}

// ---- pure helpers ----

export function newGuid(): string {
  // randomUUID needs a secure context; plain http on a LAN address has getRandomValues but not it
  const c = globalThis.crypto as Crypto | undefined;
  if (c && typeof c.randomUUID === "function") return c.randomUUID();
  const bytes = new Uint8Array(16);
  if (c) c.getRandomValues(bytes);
  else for (let i = 0; i < 16; i++) bytes[i] = Math.floor(Math.random() * 256);
  bytes[6] = (bytes[6] & 0x0f) | 0x40;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/** A deep copy of a model, so an edit never reaches into the object the page compares against. */
export function cloneModel(model: ModelJson): ModelJson {
  return JSON.parse(JSON.stringify(model)) as ModelJson;
}

export function fullName(t: { CodeName: string; Namespace?: string | null }): string {
  return t.Namespace ? `${t.Namespace}.${t.CodeName}` : t.CodeName;
}

/** Every type except the built-in base, the order the lists show them in. */
export function typeList(model: ModelJson, baseTypeId: string): NodeTypeJson[] {
  return Object.values(model.NodeTypes)
    .filter((t) => t.Id !== baseTypeId)
    .sort((a, b) => a.CodeName.localeCompare(b.CodeName) || (a.Namespace ?? "").localeCompare(b.Namespace ?? ""));
}

export function relationList(model: ModelJson): RelationJson[] {
  return Object.values(model.Relations).sort((a, b) => a.CodeName.localeCompare(b.CodeName));
}

/** The properties a type has of its own plus what it inherits, with the owner of each. */
export function allProperties(model: ModelJson, typeId: string, baseTypeId: string): { property: PropertyJson; owner: NodeTypeJson; inherited: boolean }[] {
  const out: { property: PropertyJson; owner: NodeTypeJson; inherited: boolean }[] = [];
  const seen = new Set<string>();
  const visit = (id: string, inherited: boolean, depth: number) => {
    if (depth > 50) return;
    const t = model.NodeTypes[id];
    if (!t) return;
    for (const p of Object.values(t.Properties)) {
      if (seen.has(p.Id)) continue;
      seen.add(p.Id);
      out.push({ property: p, owner: t, inherited });
    }
    for (const parent of t.Parents ?? []) if (parent !== baseTypeId) visit(parent, true, depth + 1);
  };
  visit(typeId, false, 0);
  return out;
}

export function descendants(model: ModelJson, typeId: string): NodeTypeJson[] {
  return Object.values(model.NodeTypes).filter((t) => (t.Parents ?? []).includes(typeId));
}

/** The relations a type takes part in, on either side, itself or through a parent. */
export function relationsOf(model: ModelJson, typeId: string, baseTypeId: string): { relation: RelationJson; asSource: boolean; asTarget: boolean }[] {
  const lineage = new Set<string>();
  const walk = (id: string, depth: number) => {
    if (depth > 50 || lineage.has(id)) return;
    lineage.add(id);
    for (const p of model.NodeTypes[id]?.Parents ?? []) if (p !== baseTypeId) walk(p, depth + 1);
  };
  walk(typeId, 0);
  const out: { relation: RelationJson; asSource: boolean; asTarget: boolean }[] = [];
  for (const r of Object.values(model.Relations)) {
    const asSource = r.SourceTypes.some((id) => lineage.has(id));
    const asTarget = r.TargetTypes.some((id) => lineage.has(id));
    if (asSource || asTarget) out.push({ relation: r, asSource, asTarget });
  }
  return out;
}

// ---- colors ----

/** Ten hues that stay apart in both themes. A source keeps its color by position in the source list. */
const sourcePalette = ["#2f7fd6", "#d97b2b", "#3ca35a", "#b84cc0", "#c9a227", "#d64f5f", "#2ba8a0", "#7a6ff0", "#8a8a2b", "#e06aa2"];

export function sourceColor(index: number): string {
  return sourcePalette[((index % sourcePalette.length) + sourcePalette.length) % sourcePalette.length];
}

/**
 * The id of the synthetic source of types registered from application code (OnDatamodelInit). It is
 * a fixed guid on the server (DatamodelSource.CodeSourceId), so pages that show types without asking
 * for the whole model - the query type picker, the dashboard - can still tell it apart.
 */
export const codeSourceGuid = "00000000-0000-0000-0000-00000000c0de";

/**
 * A colour per source id, by position in the source list, so every page marks a type with the same
 * colour. The code source always gets grey: it is not one of the configured sources and its position
 * would otherwise shift the others' colours depending on whether it happens to be in the list.
 */
export function sourceColors(sources: { id: string; type?: string }[], codeSourceId: string = codeSourceGuid): Map<string, string> {
  const map = new Map<string, string>();
  let i = 0;
  for (const s of sources) {
    if (s.id === codeSourceId || s.type === "Code") map.set(s.id, "#8a8781");
    else map.set(s.id, sourceColor(i++));
  }
  return map;
}

// ---- search ----

export type HitKind = "type" | "property" | "relation" | "source";

export interface SearchHit {
  kind: HitKind;
  id: string;
  /** for a property: the type it sits on */
  typeId?: string;
  label: string;
  detail: string;
  score: number;
}

/**
 * A ranked search over everything the model names: types, properties, relations and sources. A
 * model is small enough that a scan per keystroke is nothing, so there is no index to keep right.
 */
export function searchModel(model: ModelJson, sources: SourceInfo[], query: string, baseTypeId: string): SearchHit[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const hits: SearchHit[] = [];
  const score = (text: string | null | undefined): number => {
    if (!text) return 0;
    const t = text.toLowerCase();
    if (t === q) return 100;
    if (t.startsWith(q)) return 60;
    if (t.includes(q)) return 30;
    return 0;
  };
  for (const t of Object.values(model.NodeTypes)) {
    if (t.Id === baseTypeId) continue;
    const s = Math.max(score(t.CodeName), score(fullName(t)) - 5, score(t.Id) - 20);
    if (s > 0) hits.push({ kind: "type", id: t.Id, label: t.CodeName, detail: t.Namespace ?? "", score: s + 5 });
    for (const p of Object.values(t.Properties)) {
      const ps = Math.max(score(p.CodeName), score(`${t.CodeName}.${p.CodeName}`) - 5, score(p.Id) - 20);
      if (ps > 0) hits.push({ kind: "property", id: p.Id, typeId: t.Id, label: `${t.CodeName}.${p.CodeName}`, detail: p.PropertyType, score: ps });
    }
  }
  for (const r of Object.values(model.Relations)) {
    const s = Math.max(score(r.CodeName), score(fullName(r)) - 5, score(r.CodeNameSources), score(r.CodeNameTargets), score(r.Id) - 20);
    if (s > 0) hits.push({ kind: "relation", id: r.Id, label: r.CodeName, detail: r.RelationType, score: s + 2 });
  }
  for (const s of sources) {
    const sc = Math.max(score(s.name), score(s.namespace), score(s.filepath), score(s.reference));
    if (sc > 0) hits.push({ kind: "source", id: s.id, label: s.name, detail: s.type, score: sc });
  }
  return hits.sort((a, b) => b.score - a.score || a.label.localeCompare(b.label)).slice(0, 50);
}

// ---- comparing two models ----

export interface ModelDiff {
  addedTypes: string[];
  removedTypes: string[];
  changedTypes: string[];
  addedRelations: string[];
  removedRelations: string[];
  changedRelations: string[];
  sourcesChanged: boolean;
  /** true when nothing differs */
  same: boolean;
}

/** Compares two models by id and content, ignoring where things came from (source id and file). */
export function diffModels(a: ModelJson, b: ModelJson, baseTypeId: string): ModelDiff {
  const fp = (o: object): string => {
    const copy = { ...(o as Record<string, unknown>) };
    delete copy.DatamodelSourceId;
    delete copy.DatamodelSourceFilename;
    return JSON.stringify(copy, Object.keys(copy).sort());
  };
  const diff: ModelDiff = { addedTypes: [], removedTypes: [], changedTypes: [], addedRelations: [], removedRelations: [], changedRelations: [], sourcesChanged: false, same: true };
  for (const id of Object.keys(b.NodeTypes)) {
    if (id === baseTypeId) continue;
    if (!a.NodeTypes[id]) diff.addedTypes.push(id);
    else if (fp(a.NodeTypes[id]) !== fp(b.NodeTypes[id])) diff.changedTypes.push(id);
  }
  for (const id of Object.keys(a.NodeTypes)) if (id !== baseTypeId && !b.NodeTypes[id]) diff.removedTypes.push(id);
  for (const id of Object.keys(b.Relations)) {
    if (!a.Relations[id]) diff.addedRelations.push(id);
    else if (fp(a.Relations[id]) !== fp(b.Relations[id])) diff.changedRelations.push(id);
  }
  for (const id of Object.keys(a.Relations)) if (!b.Relations[id]) diff.removedRelations.push(id);
  diff.sourcesChanged = JSON.stringify(a.Sources ?? []) !== JSON.stringify(b.Sources ?? []);
  // a type whose only difference is its source or file still has to count as changed for the page,
  // since that is what decides which file it is written to
  for (const id of Object.keys(b.NodeTypes)) {
    if (id === baseTypeId || !a.NodeTypes[id] || diff.changedTypes.includes(id)) continue;
    const x = a.NodeTypes[id];
    const y = b.NodeTypes[id];
    if (x.DatamodelSourceId !== y.DatamodelSourceId || (x.DatamodelSourceFilename ?? "") !== (y.DatamodelSourceFilename ?? "")) diff.changedTypes.push(id);
  }
  diff.same =
    diff.addedTypes.length + diff.removedTypes.length + diff.changedTypes.length + diff.addedRelations.length + diff.removedRelations.length + diff.changedRelations.length === 0 &&
    !diff.sourcesChanged;
  return diff;
}
