using System.Text.Json.Serialization;
namespace Relatude.DB.Datamodels;
public class RelationModel {
    public Guid Id { get; set; }
    public string? Namespace { get; set; } = string.Empty;
    public string CodeName { get; set; } = string.Empty;
    public string FullName()=> string.IsNullOrEmpty(Namespace) ? CodeName : Namespace + "." + CodeName;
    public RelationType RelationType { get; set; }
    public List<Guid> SourceTypes { get; set; } = new();
    public List<Guid> TargetTypes { get; set; } = new();
    public string? CodeNameSources { get; set; }
    public string? CodeNameTargets { get; set; }
    public int MaxCountTo { get; set; } = int.MaxValue;
    public int MaxCountFrom { get; set; } = int.MaxValue;
    public bool CultureSpecific { get; set; }
    public bool AutoGenerated { get; internal set; }
    override public string ToString() => string.IsNullOrEmpty(Namespace) ? CodeName : Namespace + "." + CodeName;
    [JsonIgnore]
    public Type? RelationClassType; // the type of the relation class, e.g. Relation<Source, Target>
}
