using System.Text.Json.Serialization;
namespace Relatude.DB.Datamodels;
public class RelationModel {
    public Guid Id { get; set; }
    public Guid DatamodelSourceId { get; set; }
    /// <summary>
    /// When the relation comes from a file-based datamodel source, the file it was defined in,
    /// relative to the source folder. Null for non-file sources.
    /// </summary>
    public string? DatamodelSourceFilename { get; set; }
    public string? Namespace { get; set; } = string.Empty;
    public string CodeName { get; set; } = string.Empty;
    public string FullName()=> string.IsNullOrEmpty(Namespace) ? CodeName : Namespace + "." + CodeName;
    public RelationType RelationType { get; set; }
    public List<Guid> SourceTypes { get; set; } = new();
    public List<Guid> TargetTypes { get; set; } = new();
    public string? CodeNameSources { get; set; }
    public string? CodeNameTargets { get; set; }
    public int MaxCountTo { get; set; } = int.MaxValue;
    public int MaxCountFrom { get; set; } = int.MaxValue;
    public bool CultureSpecific { get; set; }
    [JsonInclude]
    public bool AutoGenerated { get; internal set; }
    public bool DisallowCircularReferences { get; set; }

    override public string ToString() => string.IsNullOrEmpty(Namespace) ? CodeName : Namespace + "." + CodeName;
    [JsonIgnore]
    public Type? RelationClassType; // the type of the relation class, e.g. Relation<Source, Target>
}
