using Relatude.DB.Datamodels;
using Relatude.DB.Datamodels.Properties;

namespace Relatude.DB.Cli;

/// <summary>What to show, shared by the schema and validate commands.</summary>
public sealed class SchemaFilter {
    public bool IncludeNative { get; init; }
    public bool ShowIds { get; init; }
    public bool PropertiesOnly { get; init; }
    public string[] Types { get; init; } = [];

    public bool Includes(NodeTypeModel t)
        => (IncludeNative || !ModelSource.IsNative(t))
        && (Types.Length == 0 || Types.Any(n => matches(n, t.CodeName, t.FullName)));
    public bool Includes(RelationModel r)
        => !PropertiesOnly && (IncludeNative || !ModelSource.IsNative(r))
        && (Types.Length == 0 || Types.Any(n => matches(n, r.CodeName, r.FullName())));
    static bool matches(string given, string codeName, string fullName)
        => string.Equals(given, codeName, StringComparison.OrdinalIgnoreCase)
        || string.Equals(given, fullName, StringComparison.OrdinalIgnoreCase);
}

/// <summary>Renders a datamodel as text, markdown or JSON.</summary>
public static class SchemaView {

    public static IEnumerable<NodeTypeModel> NodeTypes(Datamodel dm, SchemaFilter filter)
        => dm.NodeTypes.Values.Where(filter.Includes).OrderBy(t => t.Namespace).ThenBy(t => t.CodeName);
    public static IEnumerable<RelationModel> Relations(Datamodel dm, SchemaFilter filter)
        => dm.Relations.Values.Where(filter.Includes).OrderBy(r => r.Namespace).ThenBy(r => r.CodeName);

    public static void WriteText(Datamodel dm, SchemaFilter filter) {
        var nodeTypes = NodeTypes(dm, filter).ToList();
        var relations = Relations(dm, filter).ToList();
        Output.WriteLine($"{nodeTypes.Count} node type(s), {relations.Count} relation(s), "
            + $"{nodeTypes.Sum(t => t.Properties.Count)} declared propert(ies)");
        foreach (var group in nodeTypes.GroupBy(t => t.Namespace ?? string.Empty)) {
            Output.WriteLine();
            Output.WriteLine(group.Key.Length == 0 ? "(no namespace)" : group.Key);
            foreach (var t in group) {
                var parents = t.Parents.Where(p => p != NodeConstants.BaseNodeTypeId)
                    .Select(p => dm.NodeTypes.TryGetValue(p, out var pt) ? pt.CodeName : p.ToString()).ToArray();
                var header = "  " + t.CodeName + "  (" + t.ModelType.ToString().ToLowerInvariant() + ")";
                if (parents.Length > 0) header += " : " + string.Join(", ", parents);
                foreach (var note in typeNotes(t, dm)) header += "  " + note;
                Output.WriteLine(header);
                if (filter.ShowIds) Output.WriteLine("      id " + t.Id);
                var rows = new List<(string, string)>();
                foreach (var p in t.Properties.Values.Where(p => !p.Internal).OrderBy(p => p.CodeName)) {
                    var notes = PropertyNotes(p, t, dm);
                    var value = PropertyTypeName(p, dm);
                    if (notes.Length > 0) value += "   " + string.Join(", ", notes);
                    if (filter.ShowIds) value += "   " + p.Id;
                    rows.Add((p.CodeName, value));
                }
                if (rows.Count > 0) Output.Table(rows, "      ");
                var inherited = t.AllProperties.Values.Count(p => !p.Internal) - t.Properties.Count(p => !p.Value.Internal);
                if (inherited > 0) Output.WriteLine($"      ({inherited} inherited)");
            }
        }
        if (relations.Count > 0) {
            Output.WriteLine();
            Output.WriteLine("Relations");
            foreach (var r in relations) {
                var line = "  " + r.FullName() + "  " + r.RelationType + "  " + Endpoints(r, dm);
                if (r.AutoGenerated) line += "  auto";
                if (r.DisallowCircularReferences) line += "  no cycles";
                if (r.CultureSpecific) line += "  culture specific";
                Output.WriteLine(line);
                if (filter.ShowIds) Output.WriteLine("      id " + r.Id);
            }
        }
    }

    public static void WriteMarkdown(Datamodel dm, SchemaFilter filter) {
        var nodeTypes = NodeTypes(dm, filter).ToList();
        var relations = Relations(dm, filter).ToList();
        Output.WriteLine("# Datamodel");
        Output.WriteLine();
        Output.WriteLine($"{nodeTypes.Count} node types, {relations.Count} relations.");
        foreach (var group in nodeTypes.GroupBy(t => t.Namespace ?? string.Empty)) {
            Output.WriteLine();
            Output.WriteLine("## " + (group.Key.Length == 0 ? "(no namespace)" : group.Key));
            foreach (var t in group) {
                Output.WriteLine();
                var parents = t.Parents.Where(p => p != NodeConstants.BaseNodeTypeId)
                    .Select(p => dm.NodeTypes.TryGetValue(p, out var pt) ? pt.CodeName : p.ToString()).ToArray();
                Output.WriteLine("### " + t.CodeName + (parents.Length > 0 ? " : " + string.Join(", ", parents) : string.Empty));
                Output.WriteLine();
                var notes = typeNotes(t, dm).ToList();
                if (filter.ShowIds) notes.Insert(0, "`" + t.Id + "`");
                Output.WriteLine("*" + t.ModelType.ToString().ToLowerInvariant() + "*" + (notes.Count > 0 ? " — " + string.Join(", ", notes) : string.Empty));
                var props = t.Properties.Values.Where(p => !p.Internal).OrderBy(p => p.CodeName).ToList();
                if (props.Count == 0) continue;
                Output.WriteLine();
                Output.WriteLine("| Member | Type | Notes |" + (filter.ShowIds ? " Id |" : string.Empty));
                Output.WriteLine("| --- | --- | --- |" + (filter.ShowIds ? " --- |" : string.Empty));
                foreach (var p in props) {
                    Output.WriteLine("| " + p.CodeName + " | `" + PropertyTypeName(p, dm) + "` | "
                        + string.Join(", ", PropertyNotes(p, t, dm)) + " |"
                        + (filter.ShowIds ? " `" + p.Id + "` |" : string.Empty));
                }
            }
        }
        if (relations.Count == 0) return;
        Output.WriteLine();
        Output.WriteLine("## Relations");
        Output.WriteLine();
        Output.WriteLine("| Relation | Shape | Endpoints |" + (filter.ShowIds ? " Id |" : string.Empty));
        Output.WriteLine("| --- | --- | --- |" + (filter.ShowIds ? " --- |" : string.Empty));
        foreach (var r in relations) {
            Output.WriteLine("| " + r.FullName() + " | " + r.RelationType + " | " + Endpoints(r, dm) + " |"
                + (filter.ShowIds ? " `" + r.Id + "` |" : string.Empty));
        }
    }

    /// <summary>The JSON shape: ids included, so a caller can build raw queries and property paths from it.</summary>
    public static object BuildJson(Datamodel dm, SchemaFilter filter) => new {
        NodeTypes = NodeTypes(dm, filter).Select(t => new {
            t.Id,
            t.CodeName,
            t.FullName,
            t.Namespace,
            ModelType = t.ModelType.ToString(),
            Parents = t.Parents.Where(p => p != NodeConstants.BaseNodeTypeId)
                .Select(p => dm.NodeTypes.TryGetValue(p, out var pt) ? pt.FullName : p.ToString()).ToArray(),
            Descendants = t.ThisAndDescendingTypes.Values.Where(d => d.Id != t.Id).Select(d => d.FullName).ToArray(),
            TextIndex = t.TextIndex == true,
            SemanticIndex = t.SemanticIndex == true,
            t.Hidden,
            t.IsInnerNode,
            IdMember = t.NameOfPublicIdProperty,
            DisplayNameMember = t.NameOfDisplayNameProperty,
            AddressMember = t.NameOfAddressProperty,
            MetaMember = t.NameOfMetaProperty,
            Properties = t.Properties.Values.Where(p => !p.Internal).OrderBy(p => p.CodeName).Select(p => propertyJson(p, t, dm)).ToArray(),
            InheritedProperties = t.AllProperties.Values.Where(p => !p.Internal && !t.Properties.ContainsKey(p.Id))
                .OrderBy(p => p.CodeName).Select(p => propertyJson(p, t, dm)).ToArray(),
        }).ToArray(),
        Relations = Relations(dm, filter).Select(r => new {
            r.Id,
            r.CodeName,
            FullName = r.FullName(),
            r.Namespace,
            RelationType = r.RelationType.ToString(),
            SourceTypes = r.SourceTypes.Select(id => name(dm, id)).ToArray(),
            TargetTypes = r.TargetTypes.Select(id => name(dm, id)).ToArray(),
            r.CodeNameSources,
            r.CodeNameTargets,
            r.AutoGenerated,
            r.DisallowCircularReferences,
            r.CultureSpecific,
        }).ToArray(),
    };
    static object propertyJson(PropertyModel p, NodeTypeModel t, Datamodel dm) => new {
        p.Id,
        p.CodeName,
        Type = PropertyTypeName(p, dm),
        PropertyType = p.PropertyType.ToString(),
        DeclaredBy = dm.NodeTypes.TryGetValue(p.NodeType, out var owner) ? owner.FullName : null,
        p.Indexed,
        Facet = p.Indexed && !p.NotFacet,
        p.UniqueValues,
        p.CultureSensitive,
        p.DisplayName,
        Notes = PropertyNotes(p, t, dm),
        Relation = p is RelationPropertyModel rp && dm.Relations.TryGetValue(rp.RelationId, out var rel) ? rel.FullName() : null,
        RelatedTypes = p is RelationPropertyModel r ? RelatedTypes(r, dm).Select(x => x.FullName).ToArray()
            : p is ReferencePropertyModel rf ? rf.NodeTypes.Select(id => name(dm, id)).ToArray()
            : p is ReferencesPropertyModel rs ? rs.NodeTypes.Select(id => name(dm, id)).ToArray()
            : null,
    };
    static string name(Datamodel dm, Guid nodeTypeId)
        => dm.NodeTypes.TryGetValue(nodeTypeId, out var t) ? t.FullName : nodeTypeId.ToString();

    public static string Endpoints(RelationModel r, Datamodel dm) {
        var sources = string.Join(" | ", r.SourceTypes.Select(id => dm.NodeTypes.TryGetValue(id, out var t) ? t.CodeName : id.ToString()));
        var targets = string.Join(" | ", r.TargetTypes.Select(id => dm.NodeTypes.TryGetValue(id, out var t) ? t.CodeName : id.ToString()));
        var arrow = r.RelationType switch {
            RelationType.OneOne => "1 - 1",
            RelationType.OneToOne => "1 -> 1",
            RelationType.OneToMany => "1 -> *",
            RelationType.ManyMany => "* - *",
            RelationType.ManyToMany => "* -> *",
            _ => "?",
        };
        return (sources.Length == 0 ? "?" : sources) + " " + arrow + " " + (targets.Length == 0 ? "?" : targets);
    }

    /// <summary>The C# type a member of this property has, as it appears in the model code.</summary>
    public static string PropertyTypeName(PropertyModel p, Datamodel dm) {
        switch (p) {
            case IntegerPropertyModel i when i.IsEnum:
                return shortName(i.FullEnumTypeName) ?? "int";
            case EnumArrayPropertyModel e:
                return (shortName(e.FullEnumTypeName) ?? "int") + "[]";
            case RelationPropertyModel r: {
                    var related = RelatedTypes(r, dm);
                    var name = related.Length == 0 ? "?" : string.Join(" | ", related.Select(t => t.CodeName));
                    return r.IsMany ? name + "[]" : name;
                }
            case ReferencesPropertyModel rs:
                return "References<" + referenceTarget(rs.NodeTypes, dm) + ">";
            case ReferencePropertyModel rf:
                return "Reference<" + referenceTarget(rf.NodeTypes, dm) + ">";
            case EmbeddedPropertyModel em: {
                    var inner = referenceTarget(em.InnerNodeTypes, dm);
                    if (em.EmbeddedValueType == EmbeddedValueType.InnerNodeMap) {
                        var key = em.KeyPropertyName ?? "key";
                        return "EmbeddedMap<" + key + ", " + inner + ">";
                    }
                    return "Embedded<" + inner + ">";
                }
        }
        return p.PropertyType switch {
            PropertyType.Boolean => "bool",
            PropertyType.Integer => "int",
            PropertyType.Long => "long",
            PropertyType.Double => "double",
            PropertyType.Float => "float",
            PropertyType.Decimal => "decimal",
            PropertyType.String => "string",
            PropertyType.StringArray => "string[]",
            PropertyType.Guid => "Guid",
            PropertyType.GuidArray => "Guid[]",
            PropertyType.DateTime => "DateTime",
            PropertyType.DateTimeOffset => "DateTimeOffset",
            PropertyType.TimeSpan => "TimeSpan",
            PropertyType.ByteArray => "byte[]",
            PropertyType.FloatArray => "float[]",
            PropertyType.GeoCoordinate => "GeoCoordinate",
            PropertyType.File => "FileValue",
            _ => p.PropertyType.ToString(),
        };
    }
    /// <summary>What a relation property points at.</summary>
    public static NodeTypeModel[] RelatedTypes(RelationPropertyModel p, Datamodel dm)
        => dm.NodeTypes.TryGetValue(p.NodeTypeOfRelated, out var related) ? [related] : [];

    static string referenceTarget(List<Guid> ids, Datamodel dm) {
        if (ids.Count == 0) return "?";
        return string.Join(" | ", ids.Select(id => dm.NodeTypes.TryGetValue(id, out var t) ? t.CodeName : id.ToString()));
    }
    static string? shortName(string? fullName) {
        if (string.IsNullOrEmpty(fullName)) return null;
        var i = fullName.LastIndexOf('.');
        return i < 0 ? fullName : fullName[(i + 1)..];
    }

    /// <summary>Everything about a property that changes how it behaves: indexes, constraints, markers.</summary>
    public static string[] PropertyNotes(PropertyModel p, NodeTypeModel t, Datamodel dm) {
        var notes = new List<string>();
        if (p.CodeName == t.NameOfDisplayNameProperty) notes.Add("display name");
        if (p.CodeName == t.NameOfAddressProperty) notes.Add("address");
        if (p.CodeName == t.NameOfCreatedUtcProperty) notes.Add("created utc");
        if (p.CodeName == t.NameOfChangedUtcProperty) notes.Add("changed utc");
        if (p.Indexed) notes.Add("indexed");
        if (p.Indexed && !p.NotFacet && p is not RelationPropertyModel) notes.Add("facet");
        if (p is RelationPropertyModel rel && rel.Facet) notes.Add("facet");
        if (p.UniqueValues) notes.Add("unique");
        if (p.CultureSensitive) notes.Add("culture sensitive");
        if (p.IndexBoost != 0) notes.Add("boost " + p.IndexBoost);
        if (p.IndexType != IndexStorageType.Default) notes.Add(p.IndexType.ToString().ToLowerInvariant() + " index");
        switch (p) {
            case StringPropertyModel s:
                if (s.IndexedByWords) notes.Add("word index");
                if (s.IndexedBySemantic) notes.Add("semantic index");
                if (s.PrefixSearch) notes.Add("prefix search");
                if (s.InfixSearch) notes.Add("infix search");
                if (s.MaxLength != int.MaxValue) notes.Add("max length " + s.MaxLength);
                if (s.MinLength != 0) notes.Add("min length " + s.MinLength);
                if (!string.IsNullOrEmpty(s.RegularExpression)) notes.Add("pattern " + s.RegularExpression);
                if (!string.IsNullOrEmpty(s.DefaultValue)) notes.Add("default \"" + s.DefaultValue + "\"");
                break;
            case IntegerPropertyModel i:
                if (i.MinValue != int.MinValue) notes.Add("min " + i.MinValue);
                if (i.MaxValue != int.MaxValue) notes.Add("max " + i.MaxValue);
                // an enum's legal values are its members, which the type name already says
                if (i.LegalValues != null && !i.IsEnum) notes.Add("legal values " + string.Join("/", i.LegalValues));
                if (i.DefaultValue != 0) notes.Add("default " + i.DefaultValue);
                break;
            case RelationPropertyModel r:
                if (dm.Relations.TryGetValue(r.RelationId, out var relation)) notes.Add("relation " + relation.CodeName);
                if (r.FromTargetToSource) notes.Add("inbound side");
                if (r.TextIndexRelatedContent) notes.Add("indexes related content");
                else if (r.TextIndexRelatedDisplayName) notes.Add("indexes related display name");
                break;
            case ReferencePropertyModel or ReferencesPropertyModel:
                notes.Add("reference, not a graph edge");
                break;
        }
        if (p.ExcludeFromTextIndex && p is StringPropertyModel) notes.Add("excluded from text index");
        return [.. notes];
    }
    static IEnumerable<string> typeNotes(NodeTypeModel t, Datamodel dm) {
        if (t.TextIndex == true) yield return "text index";
        if (t.SemanticIndex == true) yield return "semantic index";
        if (t.Hidden) yield return "hidden";
        if (t.IsInnerNode) yield return "embedded only";
        if (t.MinNoInstances != int.MinValue) yield return "min " + t.MinNoInstances + " instances";
        if (t.MaxNoInstances != int.MaxValue) yield return "max " + t.MaxNoInstances + " instances";
        var descendants = t.ThisAndDescendingTypes.Values.Count(d => d.Id != t.Id);
        if (descendants > 0) yield return descendants + " descendant type(s)";
    }
}
