<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.2.0.122</Version>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GraphQL-Parser" Version="9.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Relatude.DB.DataStore\Relatude.DB.DataStore.csproj" />
  </ItemGroup>

</Project>
