// <auto-generated>
//     This file was generated by Relatude.DB from the data model (source "New source").
//     Do not edit it. Every file in this folder is deleted and generated again each time the data
//     model is activated, so any change made here is lost then. Change the model in the data model
//     editor instead.
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Models6 {

    [Relatude.DB.Nodes.Node(Id = "248d5ef2-e38d-439d-8b75-2d1ce337a431")]
    public class NewType22 {
        [Relatude.DB.Nodes.DoubleProperty(Id = "5fb5132c-df72-4ba2-8e07-a6e0acabcd0f")]
        public double NewProperty { get; set; }
    }

}
