using System.Text;
using Relatude.DB.GraphQL.Schema;

namespace Relatude.DB.GraphQL.Endpoints;

/// <summary>Writes C# for a schema: classes a System.Text.Json client deserializes into, and a small sample client.</summary>
public static class CSharpWriter {
    const string Namespace = "GraphQLClient";

    public static string WriteTypes(GqlSchema schema) {
        var def = schema.Definition;
        var sb = new StringBuilder();
        sb.AppendLine($"// Types of the GraphQL endpoint \"{def.Name}\" ({def.Url}), generated by Relatude.DB.");
        sb.AppendLine("// Regenerate after changing the endpoint or the datamodel. Deserialize with System.Text.Json and a");
        sb.AppendLine("// JsonStringEnumConverter; property names are mapped with JsonPropertyName, so no naming policy is needed.");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace};");
        var types = schema.Types.Values
            .Where(t => t is not GqlScalarType && t != schema.QueryType && t != schema.MutationType)
            .OrderBy(rank).ThenBy(t => t.Name, StringComparer.Ordinal);
        foreach (var t in types) {
            sb.AppendLine();
            switch (t) {
                case GqlEnumType e:
                    comment(sb, e.Description);
                    sb.AppendLine("[JsonConverter(typeof(JsonStringEnumConverter))]");
                    sb.AppendLine($"public enum {e.Name} {{ {string.Join(", ", e.Values.Select(v => v.Name))} }}");
                    break;
                case GqlInterfaceType i:
                    writeClass(sb, i.Name, i.Description, i.Fields, baseOf(i.Interfaces, out var inherited), inherited, input: false);
                    break;
                case GqlObjectType o:
                    writeClass(sb, o.Name, o.Description, o.Fields, baseOf(o.Interfaces, out var inheritedFields), inheritedFields, input: false);
                    break;
                case GqlInputObjectType input:
                    comment(sb, input.Description);
                    sb.AppendLine($"public class {input.Name} {{");
                    foreach (var f in input.InputFields) property(sb, input.Name, f.Name, f.Type, input: true);
                    sb.AppendLine("}");
                    break;
            }
        }
        return Lf(sb);
    }

    internal static string Lf(StringBuilder sb) => sb.ToString().Replace("\r\n", "\n");

    static int rank(GqlNamedType t) => t switch {
        GqlEnumType => 0,
        GqlInterfaceType { Name: "Node" } => 1,
        GqlInterfaceType i => 2 + i.Interfaces.Count, // a base class before the classes deriving from it
        GqlObjectType => 10,
        GqlInputObjectType => 11,
        _ => 12,
    };

    /// <summary>The implemented interface with the most fields becomes the base class; its fields are left out of the derived class.</summary>
    static GqlInterfaceType? baseOf(List<GqlInterfaceType> interfaces, out HashSet<string> inheritedFields) {
        GqlInterfaceType? best = null;
        foreach (var i in interfaces) if (best == null || i.Fields.Count > best.Fields.Count) best = i;
        inheritedFields = best == null ? [] : new HashSet<string>(best.Fields.Select(f => f.Name), StringComparer.Ordinal);
        return best;
    }

    static void writeClass(StringBuilder sb, string name, string? description, List<GqlField> fields, GqlInterfaceType? baseType, HashSet<string> inherited, bool input) {
        comment(sb, description);
        sb.AppendLine($"public class {name}{(baseType == null ? "" : " : " + baseType.Name)} {{");
        foreach (var f in fields) {
            if (inherited.Contains(f.Name)) continue;
            property(sb, name, f.Name, f.Type, input);
        }
        sb.AppendLine("}");
    }

    static void property(StringBuilder sb, string className, string fieldName, GqlType type, bool input) {
        var propertyName = PropertyName(fieldName, className);
        var nullable = input || type is not GqlNonNullType;
        var cs = CsType(type, nullable);
        var initializer = "";
        if (!nullable) {
            if (type.UnwrapNamed() is GqlScalarType { Name: "String" or "ID" }) initializer = " = \"\";";
            else if (type is GqlNonNullType { OfType: GqlListType }) initializer = " = new();";
            else if (type.UnwrapNamed() is GqlObjectType or GqlInterfaceType) initializer = " = null!;";
        }
        sb.AppendLine($"    [JsonPropertyName(\"{fieldName}\")] public {cs} {propertyName} {{ get; set; }}{initializer}");
    }

    /// <summary>PascalCase of a field name; a property may not carry its class's name, so that one gets a suffix.</summary>
    public static string PropertyName(string fieldName, string className) {
        var name = fieldName.Length == 0 ? "Field" : char.ToUpperInvariant(fieldName[0]) + fieldName[1..];
        if (name == className) name += "Value";
        return name;
    }

    /// <summary>The C# type of a GraphQL type reference; <paramref name="nullable"/> adds the ? of a nullable position.</summary>
    public static string CsType(GqlType type, bool nullable) {
        switch (type) {
            case GqlNonNullType nn: return CsType(nn.OfType, nullable);
            case GqlListType list: return $"List<{CsType(list.OfType, list.OfType is not GqlNonNullType)}>" + (nullable ? "?" : "");
            case GqlScalarType s: {
                    var name = s.Name switch {
                        "Int" => "int",
                        "Float" => "double",
                        "Long" => "long",
                        "Decimal" => "decimal",
                        "Boolean" => "bool",
                        "DateTime" => "DateTime",
                        _ => "string",
                    };
                    return nullable ? name + "?" : name;
                }
            case GqlEnumType e: return nullable ? e.Name + "?" : e.Name;
            case GqlNamedType named: return nullable ? named.Name + "?" : named.Name;
            default: return "object?";
        }
    }

    static void comment(StringBuilder sb, string? text) {
        if (string.IsNullOrWhiteSpace(text)) return;
        sb.AppendLine($"/// <summary>{text.Replace("<", "&lt;").Replace(">", "&gt;")}</summary>");
    }

    // ---- sample client ----

    public static string WriteSample(GqlSchema schema) {
        var def = schema.Definition;
        var hasKey = !string.IsNullOrEmpty(def.ApiKey);
        var sb = new StringBuilder();
        sb.AppendLine($"// Sample client for the GraphQL endpoint \"{def.Name}\" at {def.Url}. Needs the generated types file.");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace};");
        sb.AppendLine();
        sb.AppendLine(hasKey
            ? "public sealed class GraphQLClient(HttpClient http, string endpoint, string apiKey) {"
            : "public sealed class GraphQLClient(HttpClient http, string endpoint) {");
        sb.AppendLine("    // null input values are left out of the json, so an update leaves those fields unchanged");
        sb.AppendLine("    static readonly JsonSerializerOptions _json = new() {");
        sb.AppendLine("        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
        sb.AppendLine("        Converters = { new JsonStringEnumConverter() },");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public async Task<T> QueryAsync<T>(string query, object? variables = null, CancellationToken ct = default) {");
        sb.AppendLine("        using var request = new HttpRequestMessage(HttpMethod.Post, endpoint) {");
        sb.AppendLine("            Content = JsonContent.Create(new { query, variables }, options: _json),");
        sb.AppendLine("        };");
        if (hasKey) sb.AppendLine("        request.Headers.Add(\"X-Api-Key\", apiKey);");
        sb.AppendLine("        using var response = await http.SendAsync(request, ct);");
        sb.AppendLine("        var result = await response.Content.ReadFromJsonAsync<GraphQLResponse<T>>(_json, ct)");
        sb.AppendLine("            ?? throw new InvalidOperationException(\"The endpoint returned an empty response.\");");
        sb.AppendLine("        if (result.Errors is { Count: > 0 }) throw new InvalidOperationException(string.Join(\"\\n\", result.Errors.Select(e => e.Message)));");
        sb.AppendLine("        if (result.Data is null) throw new InvalidOperationException($\"The request failed with status {(int)response.StatusCode}.\");");
        sb.AppendLine("        return result.Data;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    sealed class GraphQLResponse<T> {");
        sb.AppendLine("        [JsonPropertyName(\"data\")] public T? Data { get; set; }");
        sb.AppendLine("        [JsonPropertyName(\"errors\")] public List<GraphQLError>? Errors { get; set; }");
        sb.AppendLine("    }");
        sb.AppendLine("    sealed class GraphQLError {");
        sb.AppendLine("        [JsonPropertyName(\"message\")] public string Message { get; set; } = \"\";");
        sb.AppendLine("    }");

        var list = TypeScriptWriter.PickSampleList(schema);
        if (list == null) {
            sb.AppendLine();
            sb.AppendLine("    // The endpoint exposes no types yet, so there is nothing to query.");
            sb.AppendLine("}");
            return Lf(sb);
        }
        var wrapper = list.Type.UnwrapNamed().Name;
        var typeName = list.Type.UnwrapNamed() is GqlObjectType w && w.TryGetField("items", out var itemsField) ? itemsField.Type.UnwrapNamed().Name : "Node";
        var composite = schema.Types.TryGetValue(typeName, out var ct) ? ct as IGqlCompositeType : null;
        var selection = string.Join(" ", TypeScriptWriter.SampleFields(composite));
        var single = schema.QueryType.Fields.FirstOrDefault(f => f.Source == FieldSource.RootSingle && f.TargetNodeType == list.TargetNodeType);
        var orderBy = list.GetArgument("orderBy")?.Type.UnwrapNamed() as GqlEnumType;
        var orderArg = orderBy != null && orderBy.Values.Count > 0 ? $", orderBy: {orderBy.Values[0].Name}, descending: true" : "";
        var listProp = PropertyName(list.Name, "ListData");

        sb.AppendLine();
        sb.AppendLine($"    // A page of {list.Name}, with an optional free-text search");
        sb.AppendLine($"    public async Task<{wrapper}> List{typeName}Async(string? search = null, int page = 0) {{");
        sb.AppendLine("        var data = await QueryAsync<ListData>(\"\"\"");
        sb.AppendLine("            query List($search: String, $page: Int!) {");
        sb.AppendLine($"              {list.Name}(search: $search, page: $page, pageSize: 20{orderArg}) {{");
        sb.AppendLine("                totalCount");
        sb.AppendLine($"                items {{ {selection} }}");
        sb.AppendLine("              }");
        sb.AppendLine("            }");
        sb.AppendLine("            \"\"\", new { search, page });");
        sb.AppendLine($"        return data.{listProp};");
        sb.AppendLine("    }");
        sb.AppendLine($"    sealed class ListData {{ [JsonPropertyName(\"{list.Name}\")] public {wrapper} {listProp} {{ get; set; }} = null!; }}");

        if (single != null) {
            var singleProp = PropertyName(single.Name, "OneData");
            sb.AppendLine();
            sb.AppendLine($"    // One {typeName} by id, or null when it does not exist");
            sb.AppendLine($"    public async Task<{typeName}?> Get{typeName}Async(string id) {{");
            sb.AppendLine($"        var data = await QueryAsync<OneData>(\"query One($id: ID!) {{ {single.Name}(id: $id) {{ {selection} }} }}\", new {{ id }});");
            sb.AppendLine($"        return data.{singleProp};");
            sb.AppendLine("    }");
            sb.AppendLine($"    sealed class OneData {{ [JsonPropertyName(\"{single.Name}\")] public {typeName}? {singleProp} {{ get; set; }} }}");
        }

        var view = schema.QueryType.Fields.FirstOrDefault(f => f.Source == FieldSource.RootView);
        if (view != null) {
            var viewWrapper = view.Type.UnwrapNamed().Name;
            var viewType = view.Type.UnwrapNamed() is GqlObjectType vw && vw.TryGetField("items", out var vi) ? vi.Type.UnwrapNamed() as IGqlCompositeType : null;
            var viewProp = PropertyName(view.Name, "ViewData");
            sb.AppendLine();
            sb.AppendLine($"    // The view \"{view.Name}\": {view.Description}");
            sb.AppendLine($"    public async Task<{viewWrapper}> {PropertyName(view.Name, "GraphQLClient")}Async(int page = 0) {{");
            sb.AppendLine($"        var data = await QueryAsync<ViewData>(\"query View($page: Int!) {{ {view.Name}(page: $page, pageSize: 20) {{ totalCount items {{ {string.Join(" ", TypeScriptWriter.SampleFields(viewType))} }} }} }}\", new {{ page }});");
            sb.AppendLine($"        return data.{viewProp};");
            sb.AppendLine("    }");
            sb.AppendLine($"    sealed class ViewData {{ [JsonPropertyName(\"{view.Name}\")] public {viewWrapper} {viewProp} {{ get; set; }} = null!; }}");
        }

        if (schema.MutationType != null) {
            var create = schema.MutationType.Fields.FirstOrDefault(f => f.Source == FieldSource.MutationCreate && f.TargetNodeType == list.TargetNodeType)
                ?? schema.MutationType.Fields.FirstOrDefault(f => f.Source == FieldSource.MutationCreate);
            if (create != null) {
                var mutType = create.Type.UnwrapNamed().Name;
                var inputType = create.GetArgument("input")!.Type.UnwrapNamed().Name;
                var update = schema.MutationType.Fields.FirstOrDefault(f => f.Source == FieldSource.MutationUpdate && f.TargetNodeType == create.TargetNodeType);
                var delete = schema.MutationType.Fields.FirstOrDefault(f => f.Source == FieldSource.MutationDelete && f.TargetNodeType == create.TargetNodeType);
                var mutComposite = schema.Types.TryGetValue(mutType, out var mct) ? mct as IGqlCompositeType : null;
                var mutSelection = string.Join(" ", TypeScriptWriter.SampleFields(mutComposite));
                var createProp = PropertyName(create.Name, "CreateData");
                sb.AppendLine();
                sb.AppendLine($"    // Creates a {mutType}. Fields left null in the input take their defaults.");
                sb.AppendLine($"    public async Task<{mutType}> Create{mutType}Async({inputType} input) {{");
                sb.AppendLine($"        var data = await QueryAsync<CreateData>(\"mutation Create($input: {inputType}!) {{ {create.Name}(input: $input) {{ {mutSelection} }} }}\", new {{ input }});");
                sb.AppendLine($"        return data.{createProp};");
                sb.AppendLine("    }");
                sb.AppendLine($"    sealed class CreateData {{ [JsonPropertyName(\"{create.Name}\")] public {mutType} {createProp} {{ get; set; }} = null!; }}");
                if (update != null) {
                    var updateProp = PropertyName(update.Name, "UpdateData");
                    sb.AppendLine();
                    sb.AppendLine($"    // Updates the fields set in the input; null fields are left out of the request and stay unchanged.");
                    sb.AppendLine($"    public async Task<{mutType}> Update{mutType}Async(string id, {inputType} input) {{");
                    sb.AppendLine($"        var data = await QueryAsync<UpdateData>(\"mutation Update($id: ID!, $input: {inputType}!) {{ {update.Name}(id: $id, input: $input) {{ {mutSelection} }} }}\", new {{ id, input }});");
                    sb.AppendLine($"        return data.{updateProp};");
                    sb.AppendLine("    }");
                    sb.AppendLine($"    sealed class UpdateData {{ [JsonPropertyName(\"{update.Name}\")] public {mutType} {updateProp} {{ get; set; }} = null!; }}");
                }
                if (delete != null) {
                    var deleteProp = PropertyName(delete.Name, "DeleteData");
                    sb.AppendLine();
                    sb.AppendLine($"    // Deletes a {mutType}; false when no such node exists.");
                    sb.AppendLine($"    public async Task<bool> Delete{mutType}Async(string id) {{");
                    sb.AppendLine($"        var data = await QueryAsync<DeleteData>(\"mutation Delete($id: ID!) {{ {delete.Name}(id: $id) }}\", new {{ id }});");
                    sb.AppendLine($"        return data.{deleteProp};");
                    sb.AppendLine("    }");
                    sb.AppendLine($"    sealed class DeleteData {{ [JsonPropertyName(\"{delete.Name}\")] public bool {deleteProp} {{ get; set; }} }}");
                }
            }
        }
        sb.AppendLine("}");
        return Lf(sb);
    }
}
