using System.Text;
using Relatude.DB.GraphQL.Schema;

namespace Relatude.DB.GraphQL.Endpoints;

/// <summary>Writes TypeScript for a schema: the types a client works with, and a small sample client.</summary>
public static class TypeScriptWriter {

    public static string WriteTypes(GqlSchema schema) {
        var def = schema.Definition;
        var sb = new StringBuilder();
        sb.AppendLine($"// Types of the GraphQL endpoint \"{def.Name}\" ({def.Url}), generated by Relatude.DB.");
        sb.AppendLine("// Regenerate after changing the endpoint or the datamodel.");
        sb.AppendLine();
        sb.AppendLine("export type ID = string;");
        var types = schema.Types.Values
            .Where(t => t is not GqlScalarType)
            .OrderBy(rank).ThenBy(t => t.Name, StringComparer.Ordinal);
        foreach (var t in types) {
            sb.AppendLine();
            switch (t) {
                case GqlEnumType e:
                    comment(sb, e.Description);
                    sb.AppendLine($"export type {e.Name} = {string.Join(" | ", e.Values.Select(v => "\"" + v.Name + "\""))};");
                    break;
                case GqlInterfaceType i:
                    comment(sb, i.Description);
                    sb.Append($"export interface {i.Name}");
                    extendsClause(sb, i.Interfaces);
                    sb.AppendLine(" {");
                    foreach (var f in i.Fields) field(sb, f.Name, f.Type, optional: false);
                    sb.AppendLine("}");
                    break;
                case GqlObjectType o:
                    comment(sb, o.Description);
                    sb.Append($"export interface {o.Name}");
                    extendsClause(sb, o.Interfaces);
                    sb.AppendLine(" {");
                    if (o.NodeType != null) sb.AppendLine($"  __typename?: \"{o.Name}\";");
                    foreach (var f in o.Fields) field(sb, f.Name, f.Type, optional: false);
                    sb.AppendLine("}");
                    break;
                case GqlInputObjectType input:
                    comment(sb, input.Description);
                    sb.AppendLine($"export interface {input.Name} {{");
                    foreach (var f in input.InputFields) field(sb, f.Name, f.Type, optional: true);
                    sb.AppendLine("}");
                    break;
            }
        }
        return sb.ToString();
    }

    static int rank(GqlNamedType t) => t switch {
        GqlEnumType => 0,
        GqlInterfaceType { Name: "Node" } => 1,
        GqlInterfaceType => 2,
        GqlObjectType { Name: "Query" or "Mutation" } => 5,
        GqlObjectType => 3,
        GqlInputObjectType => 4,
        _ => 6,
    };

    static void extendsClause(StringBuilder sb, List<GqlInterfaceType> interfaces) {
        if (interfaces.Count == 0) return;
        sb.Append(" extends ");
        sb.Append(string.Join(", ", interfaces.Select(i => i.Name)));
    }

    static void field(StringBuilder sb, string name, GqlType type, bool optional) {
        var nullable = type is not GqlNonNullType;
        var ts = TsType(type);
        if (nullable) ts += " | null";
        sb.AppendLine($"  {name}{(optional ? "?" : "")}: {ts};");
    }

    /// <summary>The TypeScript type of a GraphQL type reference, without the outer nullability.</summary>
    public static string TsType(GqlType type) {
        switch (type) {
            case GqlNonNullType nn: return TsType(nn.OfType);
            case GqlListType list: {
                    var inner = TsType(list.OfType);
                    if (list.OfType is not GqlNonNullType) inner = "(" + inner + " | null)";
                    return inner + "[]";
                }
            case GqlScalarType s:
                return s.Name switch {
                    "Int" or "Float" or "Long" or "Decimal" => "number",
                    "Boolean" => "boolean",
                    "ID" => "ID",
                    _ => "string",
                };
            case GqlNamedType named: return named.Name;
            default: return "unknown";
        }
    }

    static void comment(StringBuilder sb, string? text) {
        if (string.IsNullOrWhiteSpace(text)) return;
        sb.AppendLine($"/** {text.Replace("*/", "* /")} */");
    }

    // ---- sample client ----

    public static string WriteSample(GqlSchema schema) {
        var def = schema.Definition;
        var sb = new StringBuilder();
        sb.AppendLine($"// Sample client for the GraphQL endpoint \"{def.Name}\" at {def.Url}.");
        sb.AppendLine("// The types come from the generated model file (the \"TypeScript types\" tab).");
        sb.AppendLine();
        sb.AppendLine($"const endpoint = \"{def.Url}\";");
        var hasKey = !string.IsNullOrEmpty(def.ApiKey);
        if (hasKey) sb.AppendLine("const apiKey = \"<the endpoint's api key>\";");
        sb.AppendLine();
        sb.AppendLine("export async function gql<T>(query: string, variables?: Record<string, unknown>): Promise<T> {");
        sb.AppendLine("  const response = await fetch(endpoint, {");
        sb.AppendLine("    method: \"POST\",");
        sb.AppendLine(hasKey
            ? "    headers: { \"Content-Type\": \"application/json\", \"X-Api-Key\": apiKey },"
            : "    headers: { \"Content-Type\": \"application/json\" },");
        sb.AppendLine("    body: JSON.stringify({ query, variables }),");
        sb.AppendLine("  });");
        sb.AppendLine("  const result = (await response.json()) as { data?: T; errors?: { message: string }[] };");
        sb.AppendLine("  if (result.errors?.length) throw new Error(result.errors.map((e) => e.message).join(\"\\n\"));");
        sb.AppendLine("  if (result.data === undefined) throw new Error(`The request failed with status ${response.status}`);");
        sb.AppendLine("  return result.data;");
        sb.AppendLine("}");

        var list = pickSampleList(schema);
        if (list == null) {
            sb.AppendLine();
            sb.AppendLine("// The endpoint exposes no types yet, so there is nothing to query.");
            return sb.ToString();
        }
        var typeName = list.Type.UnwrapNamed() is GqlObjectType w && w.TryGetField("items", out var itemsField) ? itemsField.Type.UnwrapNamed().Name : "Node";
        var composite = schema.Types.TryGetValue(typeName, out var ct) ? ct as IGqlCompositeType : null;
        var fields = sampleFields(composite);
        var selection = string.Join(" ", fields);
        var wrapper = list.Type.UnwrapNamed().Name;
        var single = schema.QueryType.Fields.FirstOrDefault(f => f.Source == FieldSource.RootSingle && f.TargetNodeType == list.TargetNodeType);
        var orderBy = list.GetArgument("orderBy")?.Type.UnwrapNamed() as GqlEnumType;
        var orderArg = orderBy != null && orderBy.Values.Count > 0 ? $", orderBy: {orderBy.Values[0].Name}, descending: true" : "";

        sb.AppendLine();
        sb.AppendLine($"// A page of {list.Name}, with an optional free-text search");
        sb.AppendLine($"export async function list{typeName}(search?: string, page = 0): Promise<{wrapper}> {{");
        sb.AppendLine($"  const data = await gql<{{ {list.Name}: {wrapper} }}>(");
        sb.AppendLine("    `query List($search: String, $page: Int!) {");
        sb.AppendLine($"      {list.Name}(search: $search, page: $page, pageSize: 20{orderArg}) {{");
        sb.AppendLine("        totalCount");
        sb.AppendLine($"        items {{ {selection} }}");
        sb.AppendLine("      }");
        sb.AppendLine("    }`,");
        sb.AppendLine("    { search, page },");
        sb.AppendLine("  );");
        sb.AppendLine($"  return data.{list.Name};");
        sb.AppendLine("}");

        if (single != null) {
            sb.AppendLine();
            sb.AppendLine($"// One {typeName} by id, or null when it does not exist");
            sb.AppendLine($"export async function get{typeName}(id: ID): Promise<{typeName} | null> {{");
            sb.AppendLine($"  const data = await gql<{{ {single.Name}: {typeName} | null }}>(");
            sb.AppendLine($"    `query One($id: ID!) {{ {single.Name}(id: $id) {{ {selection} }} }}`,");
            sb.AppendLine("    { id },");
            sb.AppendLine("  );");
            sb.AppendLine($"  return data.{single.Name};");
            sb.AppendLine("}");
        }

        var view = schema.QueryType.Fields.FirstOrDefault(f => f.Source == FieldSource.RootView);
        if (view != null) {
            var viewWrapper = view.Type.UnwrapNamed().Name;
            var viewType = view.Type.UnwrapNamed() is GqlObjectType vw && vw.TryGetField("items", out var vi) ? vi.Type.UnwrapNamed() as IGqlCompositeType : null;
            sb.AppendLine();
            sb.AppendLine($"// The view \"{view.Name}\": {view.Description}");
            sb.AppendLine($"export async function {view.Name}(page = 0): Promise<{viewWrapper}> {{");
            sb.AppendLine($"  const data = await gql<{{ {view.Name}: {viewWrapper} }}>(");
            sb.AppendLine($"    `query View($page: Int!) {{ {view.Name}(page: $page, pageSize: 20) {{ totalCount items {{ {string.Join(" ", sampleFields(viewType))} }} }} }}`,");
            sb.AppendLine("    { page },");
            sb.AppendLine("  );");
            sb.AppendLine($"  return data.{view.Name};");
            sb.AppendLine("}");
        }

        if (schema.MutationType != null) {
            var create = schema.MutationType.Fields.FirstOrDefault(f => f.Source == FieldSource.MutationCreate && f.TargetNodeType == list.TargetNodeType)
                ?? schema.MutationType.Fields.FirstOrDefault(f => f.Source == FieldSource.MutationCreate);
            if (create != null) {
                var mutType = create.Type.UnwrapNamed().Name;
                var inputType = create.GetArgument("input")!.Type.UnwrapNamed().Name;
                var update = schema.MutationType.Fields.FirstOrDefault(f => f.Source == FieldSource.MutationUpdate && f.TargetNodeType == create.TargetNodeType);
                var delete = schema.MutationType.Fields.FirstOrDefault(f => f.Source == FieldSource.MutationDelete && f.TargetNodeType == create.TargetNodeType);
                var mutComposite = schema.Types.TryGetValue(mutType, out var mct) ? mct as IGqlCompositeType : null;
                var mutSelection = string.Join(" ", sampleFields(mutComposite));
                sb.AppendLine();
                sb.AppendLine($"// Creates a {mutType}. Fields left out of the input take their defaults.");
                sb.AppendLine($"export async function create{mutType}(input: {inputType}): Promise<{mutType}> {{");
                sb.AppendLine($"  const data = await gql<{{ {create.Name}: {mutType} }}>(");
                sb.AppendLine($"    `mutation Create($input: {inputType}!) {{ {create.Name}(input: $input) {{ {mutSelection} }} }}`,");
                sb.AppendLine("    { input },");
                sb.AppendLine("  );");
                sb.AppendLine($"  return data.{create.Name};");
                sb.AppendLine("}");
                if (update != null) {
                    sb.AppendLine();
                    sb.AppendLine($"// Updates the given fields of a {mutType}; null clears a field, fields left out are unchanged.");
                    sb.AppendLine($"export async function update{mutType}(id: ID, input: {inputType}): Promise<{mutType}> {{");
                    sb.AppendLine($"  const data = await gql<{{ {update.Name}: {mutType} }}>(");
                    sb.AppendLine($"    `mutation Update($id: ID!, $input: {inputType}!) {{ {update.Name}(id: $id, input: $input) {{ {mutSelection} }} }}`,");
                    sb.AppendLine("    { id, input },");
                    sb.AppendLine("  );");
                    sb.AppendLine($"  return data.{update.Name};");
                    sb.AppendLine("}");
                }
                if (delete != null) {
                    sb.AppendLine();
                    sb.AppendLine($"// Deletes a {mutType}; false when no such node exists.");
                    sb.AppendLine($"export async function delete{mutType}(id: ID): Promise<boolean> {{");
                    sb.AppendLine($"  const data = await gql<{{ {delete.Name}: boolean }}>(`mutation Delete($id: ID!) {{ {delete.Name}(id: $id) }}`, {{ id }});");
                    sb.AppendLine($"  return data.{delete.Name};");
                    sb.AppendLine("}");
                }
            }
        }
        return sb.ToString();
    }

    /// <summary>A ready-to-run query for the endpoint's playground.</summary>
    public static string WriteSampleQuery(GqlSchema schema) {
        var list = pickSampleList(schema);
        if (list == null) return "{ __schema { queryType { name } } }";
        var typeName = list.Type.UnwrapNamed() is GqlObjectType w && w.TryGetField("items", out var itemsField) ? itemsField.Type.UnwrapNamed().Name : "Node";
        var composite = schema.Types.TryGetValue(typeName, out var ct) ? ct as IGqlCompositeType : null;
        var sb = new StringBuilder();
        sb.AppendLine("{");
        sb.AppendLine($"  {list.Name}(page: 0, pageSize: 5) {{");
        sb.AppendLine("    totalCount");
        sb.AppendLine($"    items {{ {string.Join(" ", sampleFields(composite))} }}");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>The list root field with the richest type, so the sample has something to show.</summary>
    static GqlField? pickSampleList(GqlSchema schema) {
        GqlField? best = null;
        var bestCount = -1;
        foreach (var f in schema.QueryType.Fields) {
            if (f.Source != FieldSource.RootList || f.TargetNodeType == null) continue;
            var count = schema.ReferenceTypesByNodeTypeId.TryGetValue(f.TargetNodeType.Id, out var t) && t is IGqlCompositeType c ? c.Fields.Count : 0;
            if (count > bestCount) { best = f; bestCount = count; }
        }
        return best;
    }

    /// <summary>id plus a few scalar fields and the first relation, as a client would select them.</summary>
    static List<string> sampleFields(IGqlCompositeType? type) {
        var fields = new List<string> { "id" };
        if (type == null) return fields;
        var scalars = 0;
        foreach (var f in type.Fields) {
            if (f.Source is FieldSource.ScalarProperty or FieldSource.EnumProperty && scalars < 4) {
                fields.Add(f.Name);
                scalars++;
            }
        }
        var relation = type.Fields.FirstOrDefault(f => f.Source is FieldSource.RelationOne or FieldSource.ReferenceOne)
            ?? type.Fields.FirstOrDefault(f => f.Source is FieldSource.RelationMany or FieldSource.ReferenceMany);
        if (relation != null) fields.Add(relation.Name + " { id displayName }");
        return fields;
    }
}
